-- password_reset_tokens.sql — SQL queries for password reset token management (feature #116).

-- name: InsertPasswordResetToken :exec
-- Inserts a new password-reset token. The token string is generated by the
-- application layer (32 random bytes, hex-encoded = 64 chars). expires_at
-- is set to now()+1h by the application layer.
INSERT INTO password_reset_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3);

-- name: GetPasswordResetToken :one
-- Fetches a password-reset token row. Returns the token, owner, expiry, and
-- used_at so the handler can perform all validity checks (single-use + TTL).
SELECT token, user_id, expires_at, used_at
FROM password_reset_tokens
WHERE token = $1;

-- name: MarkPasswordResetTokenUsed :exec
-- Stamps used_at on the token so replay attempts are rejected with 410 Gone.
UPDATE password_reset_tokens
SET used_at = now()
WHERE token = $1;
