-- Users and email-verification queries (feature #114).
-- All queries follow the naming convention: Verb + Entity, e.g. InsertUser.

-- name: InsertUser :one
-- Inserts a new user row and returns the created record.
-- The caller is responsible for normalising the email (lowercase, trimmed)
-- and supplying a bcrypt hash (cost ≥ 12) as password_hash.
INSERT INTO users (email, password_hash, preferred_locale)
VALUES ($1, $2, $3)
RETURNING id, email, preferred_locale, created_at, email_verified_at;

-- name: GetUserByEmail :one
-- Looks up a user by normalised email address. Used during login and to
-- detect duplicate-email conflicts during registration.
SELECT id, email, password_hash, preferred_locale, created_at, email_verified_at
FROM users
WHERE email = $1;

-- name: InsertEmailVerificationToken :exec
-- Inserts a new verification token. The token string is generated by the
-- application layer (32 random bytes, hex-encoded = 64 chars). expires_at
-- is set to now()+24h by the application layer.
INSERT INTO email_verification_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3);

-- name: GetEmailVerificationToken :one
-- Fetches a verification token row. Returns the token, owner, expiry, and
-- used_at so the handler can perform all validity checks.
SELECT token, user_id, expires_at, used_at
FROM email_verification_tokens
WHERE token = $1;

-- name: MarkEmailVerified :one
-- Sets email_verified_at on the user row. Returns the updated timestamps
-- so the handler can include them in the response.
UPDATE users
SET email_verified_at = now()
WHERE id = $1
RETURNING id, email, email_verified_at;

-- name: MarkVerificationTokenUsed :exec
-- Stamps used_at on the token so replay attempts are rejected with 410.
UPDATE email_verification_tokens
SET used_at = now()
WHERE token = $1;
