-- +goose Up
-- refresh_tokens stores opaque refresh tokens issued at login.
-- Each row is bound to a user; the token itself is a 64-char hex string
-- (32 random bytes) generated by the application layer.
-- Tokens are soft-revoked (revoked_at IS NOT NULL) rather than deleted so
-- that audit trails remain intact. A maintenance job prunes rows with
-- expires_at < now() periodically.
CREATE TABLE IF NOT EXISTS refresh_tokens (
    token       text          PRIMARY KEY,
    user_id     uuid          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at  timestamptz   NOT NULL,
    revoked_at  timestamptz,
    created_at  timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id
    ON refresh_tokens (user_id);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at)
    WHERE revoked_at IS NULL;

-- +goose Down
DROP INDEX IF EXISTS idx_refresh_tokens_expires_at;
DROP INDEX IF EXISTS idx_refresh_tokens_user_id;
DROP TABLE IF EXISTS refresh_tokens;
