-- +goose Up
-- password_reset_tokens stores one-time tokens issued when a user requests
-- a password reset (feature #116). Each row is bound to a user; the token
-- is a 64-char hex string (32 random bytes) generated by the application layer.
-- Tokens are single-use (used_at IS NULL == unused) and expire after 1 hour.
-- Consumed or expired tokens are retained so audit trails remain intact;
-- a maintenance job prunes rows with expires_at < now() periodically.
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token       text          PRIMARY KEY,
    user_id     uuid          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at  timestamptz   NOT NULL,
    used_at     timestamptz,
    created_at  timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id
    ON password_reset_tokens (user_id);

-- Partial index accelerates expiry sweeps (only unused tokens need TTL enforcement).
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at
    ON password_reset_tokens (expires_at)
    WHERE used_at IS NULL;

-- +goose Down
DROP INDEX IF EXISTS idx_password_reset_tokens_expires_at;
DROP INDEX IF EXISTS idx_password_reset_tokens_user_id;
DROP TABLE IF EXISTS password_reset_tokens;
