-- +goose Up
-- =====================================================================
-- arena_new — country reference: regions and a world-wide list
--
-- Until now the countries table held the 12 countries somebody once needed,
-- so an organizer in Italy could not pick Italy in the event wizard. This
-- adds:
--   * countries.region — the part of the world a client groups by, so a
--     picker shows "Europe / Latin America / ..." first and only then that
--     region's countries (not all of them at once);
--   * about 100 countries with ISO codes, the national currency and names
--     in en / ru / es (i18n_text namespace 'geo.countries').
--
-- Safe to re-run: every insert is ON CONFLICT. Existing rows keep their
-- slug and currency and only get their region set; a name already stored
-- is never overwritten.
-- =====================================================================

ALTER TABLE countries ADD COLUMN IF NOT EXISTS region text NOT NULL DEFAULT 'other';

ALTER TABLE countries DROP CONSTRAINT IF EXISTS countries_region_check;
ALTER TABLE countries ADD CONSTRAINT countries_region_check CHECK (region IN ('europe', 'north_america', 'latin_america', 'middle_east', 'asia', 'africa', 'oceania', 'other'));

COMMENT ON COLUMN countries.region IS
    'Grouping for pickers: europe, north_america, latin_america, middle_east, asia, africa, oceania or other (the default for a country added by hand).';

INSERT INTO countries (iso2, iso3, slug, currency, region) VALUES
    ('AL', 'ALB', 'albania', 'ALL', 'europe'),
    ('AD', 'AND', 'andorra', 'EUR', 'europe'),
    ('AT', 'AUT', 'austria', 'EUR', 'europe'),
    ('BY', 'BLR', 'belarus', 'BYN', 'europe'),
    ('BE', 'BEL', 'belgium', 'EUR', 'europe'),
    ('BA', 'BIH', 'bosnia-and-herzegovina', 'BAM', 'europe'),
    ('BG', 'BGR', 'bulgaria', 'EUR', 'europe'),
    ('HR', 'HRV', 'croatia', 'EUR', 'europe'),
    ('CY', 'CYP', 'cyprus', 'EUR', 'europe'),
    ('CZ', 'CZE', 'czechia', 'CZK', 'europe'),
    ('DK', 'DNK', 'denmark', 'DKK', 'europe'),
    ('EE', 'EST', 'estonia', 'EUR', 'europe'),
    ('FI', 'FIN', 'finland', 'EUR', 'europe'),
    ('FR', 'FRA', 'france', 'EUR', 'europe'),
    ('GE', 'GEO', 'georgia', 'GEL', 'europe'),
    ('DE', 'DEU', 'germany', 'EUR', 'europe'),
    ('GR', 'GRC', 'greece', 'EUR', 'europe'),
    ('HU', 'HUN', 'hungary', 'HUF', 'europe'),
    ('IS', 'ISL', 'iceland', 'ISK', 'europe'),
    ('IE', 'IRL', 'ireland', 'EUR', 'europe'),
    ('IT', 'ITA', 'italy', 'EUR', 'europe'),
    ('LV', 'LVA', 'latvia', 'EUR', 'europe'),
    ('LI', 'LIE', 'liechtenstein', 'CHF', 'europe'),
    ('LT', 'LTU', 'lithuania', 'EUR', 'europe'),
    ('LU', 'LUX', 'luxembourg', 'EUR', 'europe'),
    ('MT', 'MLT', 'malta', 'EUR', 'europe'),
    ('MD', 'MDA', 'moldova', 'MDL', 'europe'),
    ('MC', 'MCO', 'monaco', 'EUR', 'europe'),
    ('ME', 'MNE', 'montenegro', 'EUR', 'europe'),
    ('NL', 'NLD', 'netherlands', 'EUR', 'europe'),
    ('MK', 'MKD', 'north-macedonia', 'MKD', 'europe'),
    ('NO', 'NOR', 'norway', 'NOK', 'europe'),
    ('PL', 'POL', 'poland', 'PLN', 'europe'),
    ('PT', 'PRT', 'portugal', 'EUR', 'europe'),
    ('RO', 'ROU', 'romania', 'RON', 'europe'),
    ('RU', 'RUS', 'russia', 'RUB', 'europe'),
    ('SM', 'SMR', 'san-marino', 'EUR', 'europe'),
    ('RS', 'SRB', 'serbia', 'RSD', 'europe'),
    ('SK', 'SVK', 'slovakia', 'EUR', 'europe'),
    ('SI', 'SVN', 'slovenia', 'EUR', 'europe'),
    ('ES', 'ESP', 'spain', 'EUR', 'europe'),
    ('SE', 'SWE', 'sweden', 'SEK', 'europe'),
    ('CH', 'CHE', 'switzerland', 'CHF', 'europe'),
    ('UA', 'UKR', 'ukraine', 'UAH', 'europe'),
    ('GB', 'GBR', 'united-kingdom', 'GBP', 'europe'),
    ('AM', 'ARM', 'armenia', 'AMD', 'europe'),
    ('US', 'USA', 'united-states', 'USD', 'north_america'),
    ('CA', 'CAN', 'canada', 'CAD', 'north_america'),
    ('MX', 'MEX', 'mexico', 'MXN', 'latin_america'),
    ('GT', 'GTM', 'guatemala', 'GTQ', 'latin_america'),
    ('HN', 'HND', 'honduras', 'HNL', 'latin_america'),
    ('SV', 'SLV', 'el-salvador', 'USD', 'latin_america'),
    ('NI', 'NIC', 'nicaragua', 'NIO', 'latin_america'),
    ('CR', 'CRI', 'costa-rica', 'CRC', 'latin_america'),
    ('PA', 'PAN', 'panama', 'USD', 'latin_america'),
    ('CU', 'CUB', 'cuba', 'CUP', 'latin_america'),
    ('DO', 'DOM', 'dominican-republic', 'DOP', 'latin_america'),
    ('CO', 'COL', 'colombia', 'COP', 'latin_america'),
    ('VE', 'VEN', 'venezuela', 'VES', 'latin_america'),
    ('EC', 'ECU', 'ecuador', 'USD', 'latin_america'),
    ('PE', 'PER', 'peru', 'PEN', 'latin_america'),
    ('BO', 'BOL', 'bolivia', 'BOB', 'latin_america'),
    ('BR', 'BRA', 'brazil', 'BRL', 'latin_america'),
    ('PY', 'PRY', 'paraguay', 'PYG', 'latin_america'),
    ('UY', 'URY', 'uruguay', 'UYU', 'latin_america'),
    ('AR', 'ARG', 'argentina', 'ARS', 'latin_america'),
    ('CL', 'CHL', 'chile', 'CLP', 'latin_america'),
    ('IL', 'ISR', 'israel', 'ILS', 'middle_east'),
    ('TR', 'TUR', 'turkey', 'TRY', 'middle_east'),
    ('AE', 'ARE', 'united-arab-emirates', 'AED', 'middle_east'),
    ('SA', 'SAU', 'saudi-arabia', 'SAR', 'middle_east'),
    ('QA', 'QAT', 'qatar', 'QAR', 'middle_east'),
    ('JO', 'JOR', 'jordan', 'JOD', 'middle_east'),
    ('LB', 'LBN', 'lebanon', 'LBP', 'middle_east'),
    ('JP', 'JPN', 'japan', 'JPY', 'asia'),
    ('KR', 'KOR', 'south-korea', 'KRW', 'asia'),
    ('CN', 'CHN', 'china', 'CNY', 'asia'),
    ('IN', 'IND', 'india', 'INR', 'asia'),
    ('TH', 'THA', 'thailand', 'THB', 'asia'),
    ('VN', 'VNM', 'vietnam', 'VND', 'asia'),
    ('ID', 'IDN', 'indonesia', 'IDR', 'asia'),
    ('MY', 'MYS', 'malaysia', 'MYR', 'asia'),
    ('SG', 'SGP', 'singapore', 'SGD', 'asia'),
    ('PH', 'PHL', 'philippines', 'PHP', 'asia'),
    ('HK', 'HKG', 'hong-kong', 'HKD', 'asia'),
    ('TW', 'TWN', 'taiwan', 'TWD', 'asia'),
    ('KZ', 'KAZ', 'kazakhstan', 'KZT', 'asia'),
    ('AZ', 'AZE', 'azerbaijan', 'AZN', 'asia'),
    ('ZA', 'ZAF', 'south-africa', 'ZAR', 'africa'),
    ('EG', 'EGY', 'egypt', 'EGP', 'africa'),
    ('MA', 'MAR', 'morocco', 'MAD', 'africa'),
    ('TN', 'TUN', 'tunisia', 'TND', 'africa'),
    ('KE', 'KEN', 'kenya', 'KES', 'africa'),
    ('NG', 'NGA', 'nigeria', 'NGN', 'africa'),
    ('AU', 'AUS', 'australia', 'AUD', 'oceania'),
    ('NZ', 'NZL', 'new-zealand', 'NZD', 'oceania')
ON CONFLICT (iso2) DO UPDATE SET region = EXCLUDED.region;

INSERT INTO i18n_text (namespace, key, locale, value) VALUES
    ('geo.countries', 'AL', 'en', 'Albania'),
    ('geo.countries', 'AL', 'ru', 'Албания'),
    ('geo.countries', 'AL', 'es', 'Albania'),
    ('geo.countries', 'AD', 'en', 'Andorra'),
    ('geo.countries', 'AD', 'ru', 'Андорра'),
    ('geo.countries', 'AD', 'es', 'Andorra'),
    ('geo.countries', 'AT', 'en', 'Austria'),
    ('geo.countries', 'AT', 'ru', 'Австрия'),
    ('geo.countries', 'AT', 'es', 'Austria'),
    ('geo.countries', 'BY', 'en', 'Belarus'),
    ('geo.countries', 'BY', 'ru', 'Беларусь'),
    ('geo.countries', 'BY', 'es', 'Bielorrusia'),
    ('geo.countries', 'BE', 'en', 'Belgium'),
    ('geo.countries', 'BE', 'ru', 'Бельгия'),
    ('geo.countries', 'BE', 'es', 'Bélgica'),
    ('geo.countries', 'BA', 'en', 'Bosnia and Herzegovina'),
    ('geo.countries', 'BA', 'ru', 'Босния и Герцеговина'),
    ('geo.countries', 'BA', 'es', 'Bosnia y Herzegovina'),
    ('geo.countries', 'BG', 'en', 'Bulgaria'),
    ('geo.countries', 'BG', 'ru', 'Болгария'),
    ('geo.countries', 'BG', 'es', 'Bulgaria'),
    ('geo.countries', 'HR', 'en', 'Croatia'),
    ('geo.countries', 'HR', 'ru', 'Хорватия'),
    ('geo.countries', 'HR', 'es', 'Croacia'),
    ('geo.countries', 'CY', 'en', 'Cyprus'),
    ('geo.countries', 'CY', 'ru', 'Кипр'),
    ('geo.countries', 'CY', 'es', 'Chipre'),
    ('geo.countries', 'CZ', 'en', 'Czechia'),
    ('geo.countries', 'CZ', 'ru', 'Чехия'),
    ('geo.countries', 'CZ', 'es', 'Chequia'),
    ('geo.countries', 'DK', 'en', 'Denmark'),
    ('geo.countries', 'DK', 'ru', 'Дания'),
    ('geo.countries', 'DK', 'es', 'Dinamarca'),
    ('geo.countries', 'EE', 'en', 'Estonia'),
    ('geo.countries', 'EE', 'ru', 'Эстония'),
    ('geo.countries', 'EE', 'es', 'Estonia'),
    ('geo.countries', 'FI', 'en', 'Finland'),
    ('geo.countries', 'FI', 'ru', 'Финляндия'),
    ('geo.countries', 'FI', 'es', 'Finlandia'),
    ('geo.countries', 'FR', 'en', 'France'),
    ('geo.countries', 'FR', 'ru', 'Франция'),
    ('geo.countries', 'FR', 'es', 'Francia'),
    ('geo.countries', 'GE', 'en', 'Georgia'),
    ('geo.countries', 'GE', 'ru', 'Грузия'),
    ('geo.countries', 'GE', 'es', 'Georgia'),
    ('geo.countries', 'DE', 'en', 'Germany'),
    ('geo.countries', 'DE', 'ru', 'Германия'),
    ('geo.countries', 'DE', 'es', 'Alemania'),
    ('geo.countries', 'GR', 'en', 'Greece'),
    ('geo.countries', 'GR', 'ru', 'Греция'),
    ('geo.countries', 'GR', 'es', 'Grecia'),
    ('geo.countries', 'HU', 'en', 'Hungary'),
    ('geo.countries', 'HU', 'ru', 'Венгрия'),
    ('geo.countries', 'HU', 'es', 'Hungría'),
    ('geo.countries', 'IS', 'en', 'Iceland'),
    ('geo.countries', 'IS', 'ru', 'Исландия'),
    ('geo.countries', 'IS', 'es', 'Islandia'),
    ('geo.countries', 'IE', 'en', 'Ireland'),
    ('geo.countries', 'IE', 'ru', 'Ирландия'),
    ('geo.countries', 'IE', 'es', 'Irlanda'),
    ('geo.countries', 'IT', 'en', 'Italy'),
    ('geo.countries', 'IT', 'ru', 'Италия'),
    ('geo.countries', 'IT', 'es', 'Italia'),
    ('geo.countries', 'LV', 'en', 'Latvia'),
    ('geo.countries', 'LV', 'ru', 'Латвия'),
    ('geo.countries', 'LV', 'es', 'Letonia'),
    ('geo.countries', 'LI', 'en', 'Liechtenstein'),
    ('geo.countries', 'LI', 'ru', 'Лихтенштейн'),
    ('geo.countries', 'LI', 'es', 'Liechtenstein'),
    ('geo.countries', 'LT', 'en', 'Lithuania'),
    ('geo.countries', 'LT', 'ru', 'Литва'),
    ('geo.countries', 'LT', 'es', 'Lituania'),
    ('geo.countries', 'LU', 'en', 'Luxembourg'),
    ('geo.countries', 'LU', 'ru', 'Люксембург'),
    ('geo.countries', 'LU', 'es', 'Luxemburgo'),
    ('geo.countries', 'MT', 'en', 'Malta'),
    ('geo.countries', 'MT', 'ru', 'Мальта'),
    ('geo.countries', 'MT', 'es', 'Malta'),
    ('geo.countries', 'MD', 'en', 'Moldova'),
    ('geo.countries', 'MD', 'ru', 'Молдова'),
    ('geo.countries', 'MD', 'es', 'Moldavia'),
    ('geo.countries', 'MC', 'en', 'Monaco'),
    ('geo.countries', 'MC', 'ru', 'Монако'),
    ('geo.countries', 'MC', 'es', 'Mónaco'),
    ('geo.countries', 'ME', 'en', 'Montenegro'),
    ('geo.countries', 'ME', 'ru', 'Черногория'),
    ('geo.countries', 'ME', 'es', 'Montenegro'),
    ('geo.countries', 'NL', 'en', 'Netherlands'),
    ('geo.countries', 'NL', 'ru', 'Нидерланды'),
    ('geo.countries', 'NL', 'es', 'Países Bajos'),
    ('geo.countries', 'MK', 'en', 'North Macedonia'),
    ('geo.countries', 'MK', 'ru', 'Северная Македония'),
    ('geo.countries', 'MK', 'es', 'Macedonia del Norte'),
    ('geo.countries', 'NO', 'en', 'Norway'),
    ('geo.countries', 'NO', 'ru', 'Норвегия'),
    ('geo.countries', 'NO', 'es', 'Noruega'),
    ('geo.countries', 'PL', 'en', 'Poland'),
    ('geo.countries', 'PL', 'ru', 'Польша'),
    ('geo.countries', 'PL', 'es', 'Polonia'),
    ('geo.countries', 'PT', 'en', 'Portugal'),
    ('geo.countries', 'PT', 'ru', 'Португалия'),
    ('geo.countries', 'PT', 'es', 'Portugal'),
    ('geo.countries', 'RO', 'en', 'Romania'),
    ('geo.countries', 'RO', 'ru', 'Румыния'),
    ('geo.countries', 'RO', 'es', 'Rumanía'),
    ('geo.countries', 'RU', 'en', 'Russia'),
    ('geo.countries', 'RU', 'ru', 'Россия'),
    ('geo.countries', 'RU', 'es', 'Rusia'),
    ('geo.countries', 'SM', 'en', 'San Marino'),
    ('geo.countries', 'SM', 'ru', 'Сан-Марино'),
    ('geo.countries', 'SM', 'es', 'San Marino'),
    ('geo.countries', 'RS', 'en', 'Serbia'),
    ('geo.countries', 'RS', 'ru', 'Сербия'),
    ('geo.countries', 'RS', 'es', 'Serbia'),
    ('geo.countries', 'SK', 'en', 'Slovakia'),
    ('geo.countries', 'SK', 'ru', 'Словакия'),
    ('geo.countries', 'SK', 'es', 'Eslovaquia'),
    ('geo.countries', 'SI', 'en', 'Slovenia'),
    ('geo.countries', 'SI', 'ru', 'Словения'),
    ('geo.countries', 'SI', 'es', 'Eslovenia'),
    ('geo.countries', 'ES', 'en', 'Spain'),
    ('geo.countries', 'ES', 'ru', 'Испания'),
    ('geo.countries', 'ES', 'es', 'España'),
    ('geo.countries', 'SE', 'en', 'Sweden'),
    ('geo.countries', 'SE', 'ru', 'Швеция'),
    ('geo.countries', 'SE', 'es', 'Suecia'),
    ('geo.countries', 'CH', 'en', 'Switzerland'),
    ('geo.countries', 'CH', 'ru', 'Швейцария'),
    ('geo.countries', 'CH', 'es', 'Suiza'),
    ('geo.countries', 'UA', 'en', 'Ukraine'),
    ('geo.countries', 'UA', 'ru', 'Украина'),
    ('geo.countries', 'UA', 'es', 'Ucrania'),
    ('geo.countries', 'GB', 'en', 'United Kingdom'),
    ('geo.countries', 'GB', 'ru', 'Великобритания'),
    ('geo.countries', 'GB', 'es', 'Reino Unido'),
    ('geo.countries', 'AM', 'en', 'Armenia'),
    ('geo.countries', 'AM', 'ru', 'Армения'),
    ('geo.countries', 'AM', 'es', 'Armenia'),
    ('geo.countries', 'US', 'en', 'United States'),
    ('geo.countries', 'US', 'ru', 'Соединённые Штаты'),
    ('geo.countries', 'US', 'es', 'Estados Unidos'),
    ('geo.countries', 'CA', 'en', 'Canada'),
    ('geo.countries', 'CA', 'ru', 'Канада'),
    ('geo.countries', 'CA', 'es', 'Canadá'),
    ('geo.countries', 'MX', 'en', 'Mexico'),
    ('geo.countries', 'MX', 'ru', 'Мексика'),
    ('geo.countries', 'MX', 'es', 'México'),
    ('geo.countries', 'GT', 'en', 'Guatemala'),
    ('geo.countries', 'GT', 'ru', 'Гватемала'),
    ('geo.countries', 'GT', 'es', 'Guatemala'),
    ('geo.countries', 'HN', 'en', 'Honduras'),
    ('geo.countries', 'HN', 'ru', 'Гондурас'),
    ('geo.countries', 'HN', 'es', 'Honduras'),
    ('geo.countries', 'SV', 'en', 'El Salvador'),
    ('geo.countries', 'SV', 'ru', 'Сальвадор'),
    ('geo.countries', 'SV', 'es', 'El Salvador'),
    ('geo.countries', 'NI', 'en', 'Nicaragua'),
    ('geo.countries', 'NI', 'ru', 'Никарагуа'),
    ('geo.countries', 'NI', 'es', 'Nicaragua'),
    ('geo.countries', 'CR', 'en', 'Costa Rica'),
    ('geo.countries', 'CR', 'ru', 'Коста-Рика'),
    ('geo.countries', 'CR', 'es', 'Costa Rica'),
    ('geo.countries', 'PA', 'en', 'Panama'),
    ('geo.countries', 'PA', 'ru', 'Панама'),
    ('geo.countries', 'PA', 'es', 'Panamá'),
    ('geo.countries', 'CU', 'en', 'Cuba'),
    ('geo.countries', 'CU', 'ru', 'Куба'),
    ('geo.countries', 'CU', 'es', 'Cuba'),
    ('geo.countries', 'DO', 'en', 'Dominican Republic'),
    ('geo.countries', 'DO', 'ru', 'Доминиканская Республика'),
    ('geo.countries', 'DO', 'es', 'República Dominicana'),
    ('geo.countries', 'CO', 'en', 'Colombia'),
    ('geo.countries', 'CO', 'ru', 'Колумбия'),
    ('geo.countries', 'CO', 'es', 'Colombia'),
    ('geo.countries', 'VE', 'en', 'Venezuela'),
    ('geo.countries', 'VE', 'ru', 'Венесуэла'),
    ('geo.countries', 'VE', 'es', 'Venezuela'),
    ('geo.countries', 'EC', 'en', 'Ecuador'),
    ('geo.countries', 'EC', 'ru', 'Эквадор'),
    ('geo.countries', 'EC', 'es', 'Ecuador'),
    ('geo.countries', 'PE', 'en', 'Peru'),
    ('geo.countries', 'PE', 'ru', 'Перу'),
    ('geo.countries', 'PE', 'es', 'Perú'),
    ('geo.countries', 'BO', 'en', 'Bolivia'),
    ('geo.countries', 'BO', 'ru', 'Боливия'),
    ('geo.countries', 'BO', 'es', 'Bolivia'),
    ('geo.countries', 'BR', 'en', 'Brazil'),
    ('geo.countries', 'BR', 'ru', 'Бразилия'),
    ('geo.countries', 'BR', 'es', 'Brasil'),
    ('geo.countries', 'PY', 'en', 'Paraguay'),
    ('geo.countries', 'PY', 'ru', 'Парагвай'),
    ('geo.countries', 'PY', 'es', 'Paraguay'),
    ('geo.countries', 'UY', 'en', 'Uruguay'),
    ('geo.countries', 'UY', 'ru', 'Уругвай'),
    ('geo.countries', 'UY', 'es', 'Uruguay'),
    ('geo.countries', 'AR', 'en', 'Argentina'),
    ('geo.countries', 'AR', 'ru', 'Аргентина'),
    ('geo.countries', 'AR', 'es', 'Argentina'),
    ('geo.countries', 'CL', 'en', 'Chile'),
    ('geo.countries', 'CL', 'ru', 'Чили'),
    ('geo.countries', 'CL', 'es', 'Chile'),
    ('geo.countries', 'IL', 'en', 'Israel'),
    ('geo.countries', 'IL', 'ru', 'Израиль'),
    ('geo.countries', 'IL', 'es', 'Israel'),
    ('geo.countries', 'TR', 'en', 'Turkey'),
    ('geo.countries', 'TR', 'ru', 'Турция'),
    ('geo.countries', 'TR', 'es', 'Turquía'),
    ('geo.countries', 'AE', 'en', 'United Arab Emirates'),
    ('geo.countries', 'AE', 'ru', 'Объединённые Арабские Эмираты'),
    ('geo.countries', 'AE', 'es', 'Emiratos Árabes Unidos'),
    ('geo.countries', 'SA', 'en', 'Saudi Arabia'),
    ('geo.countries', 'SA', 'ru', 'Саудовская Аравия'),
    ('geo.countries', 'SA', 'es', 'Arabia Saudita'),
    ('geo.countries', 'QA', 'en', 'Qatar'),
    ('geo.countries', 'QA', 'ru', 'Катар'),
    ('geo.countries', 'QA', 'es', 'Catar'),
    ('geo.countries', 'JO', 'en', 'Jordan'),
    ('geo.countries', 'JO', 'ru', 'Иордания'),
    ('geo.countries', 'JO', 'es', 'Jordania'),
    ('geo.countries', 'LB', 'en', 'Lebanon'),
    ('geo.countries', 'LB', 'ru', 'Ливан'),
    ('geo.countries', 'LB', 'es', 'Líbano'),
    ('geo.countries', 'JP', 'en', 'Japan'),
    ('geo.countries', 'JP', 'ru', 'Япония'),
    ('geo.countries', 'JP', 'es', 'Japón'),
    ('geo.countries', 'KR', 'en', 'South Korea'),
    ('geo.countries', 'KR', 'ru', 'Южная Корея'),
    ('geo.countries', 'KR', 'es', 'Corea del Sur'),
    ('geo.countries', 'CN', 'en', 'China'),
    ('geo.countries', 'CN', 'ru', 'Китай'),
    ('geo.countries', 'CN', 'es', 'China'),
    ('geo.countries', 'IN', 'en', 'India'),
    ('geo.countries', 'IN', 'ru', 'Индия'),
    ('geo.countries', 'IN', 'es', 'India'),
    ('geo.countries', 'TH', 'en', 'Thailand'),
    ('geo.countries', 'TH', 'ru', 'Таиланд'),
    ('geo.countries', 'TH', 'es', 'Tailandia'),
    ('geo.countries', 'VN', 'en', 'Vietnam'),
    ('geo.countries', 'VN', 'ru', 'Вьетнам'),
    ('geo.countries', 'VN', 'es', 'Vietnam'),
    ('geo.countries', 'ID', 'en', 'Indonesia'),
    ('geo.countries', 'ID', 'ru', 'Индонезия'),
    ('geo.countries', 'ID', 'es', 'Indonesia'),
    ('geo.countries', 'MY', 'en', 'Malaysia'),
    ('geo.countries', 'MY', 'ru', 'Малайзия'),
    ('geo.countries', 'MY', 'es', 'Malasia'),
    ('geo.countries', 'SG', 'en', 'Singapore'),
    ('geo.countries', 'SG', 'ru', 'Сингапур'),
    ('geo.countries', 'SG', 'es', 'Singapur'),
    ('geo.countries', 'PH', 'en', 'Philippines'),
    ('geo.countries', 'PH', 'ru', 'Филиппины'),
    ('geo.countries', 'PH', 'es', 'Filipinas'),
    ('geo.countries', 'HK', 'en', 'Hong Kong'),
    ('geo.countries', 'HK', 'ru', 'Гонконг'),
    ('geo.countries', 'HK', 'es', 'Hong Kong'),
    ('geo.countries', 'TW', 'en', 'Taiwan'),
    ('geo.countries', 'TW', 'ru', 'Тайвань'),
    ('geo.countries', 'TW', 'es', 'Taiwán'),
    ('geo.countries', 'KZ', 'en', 'Kazakhstan'),
    ('geo.countries', 'KZ', 'ru', 'Казахстан'),
    ('geo.countries', 'KZ', 'es', 'Kazajistán'),
    ('geo.countries', 'AZ', 'en', 'Azerbaijan'),
    ('geo.countries', 'AZ', 'ru', 'Азербайджан'),
    ('geo.countries', 'AZ', 'es', 'Azerbaiyán'),
    ('geo.countries', 'ZA', 'en', 'South Africa'),
    ('geo.countries', 'ZA', 'ru', 'Южная Африка'),
    ('geo.countries', 'ZA', 'es', 'Sudáfrica'),
    ('geo.countries', 'EG', 'en', 'Egypt'),
    ('geo.countries', 'EG', 'ru', 'Египет'),
    ('geo.countries', 'EG', 'es', 'Egipto'),
    ('geo.countries', 'MA', 'en', 'Morocco'),
    ('geo.countries', 'MA', 'ru', 'Марокко'),
    ('geo.countries', 'MA', 'es', 'Marruecos'),
    ('geo.countries', 'TN', 'en', 'Tunisia'),
    ('geo.countries', 'TN', 'ru', 'Тунис'),
    ('geo.countries', 'TN', 'es', 'Túnez'),
    ('geo.countries', 'KE', 'en', 'Kenya'),
    ('geo.countries', 'KE', 'ru', 'Кения'),
    ('geo.countries', 'KE', 'es', 'Kenia'),
    ('geo.countries', 'NG', 'en', 'Nigeria'),
    ('geo.countries', 'NG', 'ru', 'Нигерия'),
    ('geo.countries', 'NG', 'es', 'Nigeria'),
    ('geo.countries', 'AU', 'en', 'Australia'),
    ('geo.countries', 'AU', 'ru', 'Австралия'),
    ('geo.countries', 'AU', 'es', 'Australia'),
    ('geo.countries', 'NZ', 'en', 'New Zealand'),
    ('geo.countries', 'NZ', 'ru', 'Новая Зеландия'),
    ('geo.countries', 'NZ', 'es', 'Nueva Zelanda')
ON CONFLICT (namespace, key, locale) DO NOTHING;

-- +goose Down
-- The regions go; the countries stay (sessions, venues and cities may point at them).
ALTER TABLE countries DROP CONSTRAINT IF EXISTS countries_region_check;
ALTER TABLE countries DROP COLUMN IF EXISTS region;
