// Command openapi30gen rewrites the committed pure OpenAPI 3.1 spec into a
// throwaway OpenAPI 3.0-compatible document for oapi-codegen v2.4.1, which
// does not understand the JSON Schema 2020-12 nullability idioms (checked
// again on 2026-07: the newest oapi-codegen release, v2.7.1, still rejects
// them — see https://github.com/oapi-codegen/oapi-codegen/issues/373).
//
// Rewrites applied:
//
//	type: [X, "null"]                 →  type: X            + nullable: true
//	oneOf: [$ref, {type: "null"}]     →  allOf: [$ref]      + nullable: true
//	anyOf/oneOf: [..., {type:"null"}] →  anyOf/oneOf: [...] + nullable: true
//
// Everything else round-trips through gopkg.in/yaml.v3 yaml.Node values
// unchanged: key order and scalar styles are preserved; comments are dropped,
// which is fine because only oapi-codegen consumes the output file.
//
// The committed apps/backend/openapi/openapi.yaml must stay pure OpenAPI 3.1
// — the structural tests in openapi_valid_test.go forbid the OAS 3.0-only
// `nullable:` keyword there. Only the generated compat file (never committed,
// removed by `make gen-openapi` after use) carries `nullable: true`.
//
// Usage:
//
//	go run ./apps/backend/tools/openapi30gen <input-3.1.yaml> <output-compat-3.0.yaml>
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: openapi30gen <input-openapi-3.1.yaml> <output-compat-3.0.yaml>")
		os.Exit(2)
	}
	if err := run(os.Args[1], os.Args[2]); err != nil {
		fmt.Fprintln(os.Stderr, "openapi30gen:", err)
		os.Exit(1)
	}
}

func run(inPath, outPath string) error {
	//nolint:gosec // G703: build-time CLI; the operator-supplied argv path is the point.
	data, err := os.ReadFile(filepath.Clean(inPath))
	if err != nil {
		return err
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return fmt.Errorf("parse %s: %w", inPath, err)
	}

	if err := downconvert(&doc); err != nil {
		return fmt.Errorf("downconvert %s: %w", inPath, err)
	}

	var buf bytes.Buffer
	buf.WriteString("# Code generated by apps/backend/tools/openapi30gen; DO NOT EDIT.\n")
	buf.WriteString("# OpenAPI 3.0-compat projection of apps/backend/openapi/openapi.yaml\n")
	buf.WriteString("# (3.1 null-type idioms rewritten to `nullable: true` for oapi-codegen).\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return fmt.Errorf("encode: %w", err)
	}
	if err := enc.Close(); err != nil {
		return fmt.Errorf("encode: %w", err)
	}

	//nolint:gosec // G703: build-time CLI; the operator-supplied argv path is the point.
	return os.WriteFile(filepath.Clean(outPath), buf.Bytes(), 0o600)
}

// downconvert walks the YAML document depth-first and rewrites every OpenAPI
// 3.1 null-type idiom it finds into the OAS 3.0 `nullable: true` equivalent.
func downconvert(n *yaml.Node) error {
	switch n.Kind {
	case yaml.DocumentNode, yaml.SequenceNode:
		for _, c := range n.Content {
			if err := downconvert(c); err != nil {
				return err
			}
		}
	case yaml.MappingNode:
		if err := rewriteMapping(n); err != nil {
			return err
		}
		for i := 1; i < len(n.Content); i += 2 {
			if err := downconvert(n.Content[i]); err != nil {
				return err
			}
		}
	}
	return nil
}

// rewriteMapping rewrites the 3.1 nullability idioms on a single (potential)
// schema mapping node in place, appending `nullable: true` when an idiom was
// found.
func rewriteMapping(m *yaml.Node) error {
	needNullable := false

	for i := 0; i+1 < len(m.Content); i += 2 {
		key, val := m.Content[i], m.Content[i+1]
		if key.Kind != yaml.ScalarNode || val.Kind != yaml.SequenceNode {
			continue
		}

		switch key.Value {
		case "type":
			// type: [X, "null"] → type: X
			nonNull := make([]*yaml.Node, 0, len(val.Content))
			removed := false
			for _, el := range val.Content {
				if isNullTypeScalar(el) {
					removed = true
					continue
				}
				nonNull = append(nonNull, el)
			}
			if !removed {
				continue
			}
			if len(nonNull) != 1 {
				return fmt.Errorf("line %d: type array with %d non-null entries is not downconvertible", key.Line, len(nonNull))
			}
			*val = *nonNull[0]
			needNullable = true

		case "oneOf", "anyOf":
			// oneOf: [<schema>, {type: "null"}] → allOf: [<schema>]
			kept := make([]*yaml.Node, 0, len(val.Content))
			removed := false
			for _, el := range val.Content {
				if isNullSchema(el) {
					removed = true
					continue
				}
				kept = append(kept, el)
			}
			if !removed {
				continue
			}
			if len(kept) == 0 {
				return fmt.Errorf("line %d: %s consists only of the null schema", key.Line, key.Value)
			}
			val.Content = kept
			needNullable = true
			if key.Value == "oneOf" && len(kept) == 1 {
				// A single-branch oneOf is just the wrapped schema; use
				// allOf so oapi-codegen inlines it instead of generating
				// a discriminated union wrapper.
				key.Value = "allOf"
			}
		}
	}

	if needNullable {
		m.Content = append(m.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "nullable"},
			&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"},
		)
	}
	return nil
}

// isNullTypeScalar reports whether n is the scalar "null" type entry of a
// 3.1 type array — either the quoted string "null" or a bare YAML null.
func isNullTypeScalar(n *yaml.Node) bool {
	return n.Kind == yaml.ScalarNode && (n.Value == "null" || n.Tag == "!!null")
}

// isNullSchema reports whether n is the `{type: "null"}` schema branch of a
// oneOf/anyOf union.
func isNullSchema(n *yaml.Node) bool {
	return n.Kind == yaml.MappingNode &&
		len(n.Content) == 2 &&
		n.Content[0].Kind == yaml.ScalarNode &&
		n.Content[0].Value == "type" &&
		isNullTypeScalar(n.Content[1])
}
