// Package apikeys issues and authenticates organization service credentials
// (spec §3.6 / §13.1, migration 0096, feature #512 / epic #466 W1-C1).
//
// A key is a non-JWT, server-to-server credential scoped to one organization
// (and optionally one sales channel) that a caller such as the WordPress
// "lampyris-ops" plugin presents on every request instead of a user session.
// The wire format is:
//
//	ak_<prefix12>_<secret43>
//
// `prefix12` is a 12-character random lookup key (stored verbatim in
// api_keys.key_prefix, UNIQUE) and `secret43` is a 43-character random
// secret whose bcrypt digest is stored in api_keys.key_hash. Only the
// caller ever sees the full raw string — it is generated by Issue and never
// persisted or logged. This mirrors the MACS webhook signing_secret pattern
// (hcatalog/macs_webhook.go:92): shown once, at creation time.
//
// Scope: this file (+ postgres_store.go) covers Issue, Authenticate, scope
// validation and the last-used throttle. The HTTP endpoints
// (POST/GET/DELETE .../api-keys), the applyAuth middleware wiring and the
// admin-web "API keys" tab are separate sub-features of epic #466.
package apikeys

import (
	"context"
	"crypto/rand"
	"errors"
	"math/big"
	"strings"
	"time"

	"github.com/google/uuid"
	"golang.org/x/crypto/bcrypt"
)

// BcryptCost is the work factor used when hashing the secret half of a key.
// Matches the platform-wide password cost (users.BcryptCost).
const BcryptCost = 12

// Wire-format sizing (spec §13.1: "ak_<prefix12>_<secret43>").
const (
	// KeyPrefixLen is the length of the random lookup segment.
	KeyPrefixLen = 12
	// KeySecretLen is the length of the random secret segment.
	KeySecretLen = 43
	// KeyWirePrefix is the constant leading token of every raw key.
	KeyWirePrefix = "ak_"
)

// randomAlphabet is URL-safe and avoids characters easily confused with each
// other (kept simple: full alphanumeric — the spec gives no narrower charset
// and 12/43 chars from this alphabet has ample entropy for both segments).
const randomAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

// ForbiddenScopePrefixes are permission-code prefixes that no API key may
// ever carry, regardless of what the issuing caller requests (spec §13.1:
// "любые коды permissions, кроме platform.*, admin.*, api_key.manage").
var ForbiddenScopePrefixes = []string{"platform.", "admin."}

// ForbiddenScopeExact are exact permission codes that no API key may carry.
var ForbiddenScopeExact = map[string]bool{
	"api_key.manage": true,
}

// Sentinel errors. Callers use errors.Is.
var (
	// ErrEmptyScopes is returned when Issue is called with zero scopes — a
	// key with no permissions can never do anything useful and is almost
	// certainly a caller bug.
	ErrEmptyScopes = errors.New("apikeys: at least one scope is required")

	// ErrForbiddenScope is returned by ValidateScopes / Issue when a
	// requested scope is platform.*, admin.*, or api_key.manage.
	ErrForbiddenScope = errors.New("apikeys: scope is not allowed on a service API key")

	// ErrNameRequired is returned by Issue when name is blank.
	ErrNameRequired = errors.New("apikeys: name is required")

	// ErrNotFound is returned by Authenticate when no row matches the
	// presented prefix.
	ErrNotFound = errors.New("apikeys: key not found")

	// ErrMalformed is returned by Authenticate when the raw string does not
	// match the ak_<prefix12>_<secret43> shape at all (so no DB lookup is
	// even attempted).
	ErrMalformed = errors.New("apikeys: malformed key")

	// ErrSecretMismatch is returned by Authenticate when the prefix is
	// found but the secret's bcrypt digest does not match.
	ErrSecretMismatch = errors.New("apikeys: secret does not match")

	// ErrRevoked is returned by Authenticate when the key's revoked_at is
	// set.
	ErrRevoked = errors.New("apikeys: key has been revoked")

	// ErrExpired is returned by Authenticate when the key's expires_at has
	// passed.
	ErrExpired = errors.New("apikeys: key has expired")
)

// LastUsedThrottle is the minimum interval between last_used_at writes
// (spec §13.1: "last_used_at обновляется не чаще раза в минуту").
const LastUsedThrottle = time.Minute

// APIKey is the store-facing view of an api_keys row. KeyHash is included
// so Authenticate can verify a candidate secret; it is never serialized to
// callers outside this package.
type APIKey struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	ChannelID  *uuid.UUID
	Name       string
	KeyPrefix  string
	KeyHash    string
	Scopes     []string
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	LastUsedAt *time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
}

// IsRevoked reports whether the key has been revoked.
func (k APIKey) IsRevoked() bool {
	return k.RevokedAt != nil
}

// IsExpired reports whether the key's expiry has passed as of now.
func (k APIKey) IsExpired(now time.Time) bool {
	return k.ExpiresAt != nil && !k.ExpiresAt.After(now)
}

// Store is the persistence boundary this package needs. The
// gen.Queries-backed implementation lives in postgres_store.go, following
// the same shape as internal/platform/customers.Store.
type Store interface {
	// InsertAPIKey creates a new row and returns it. channelID and
	// expiresAt may be nil.
	InsertAPIKey(ctx context.Context, orgID uuid.UUID, channelID *uuid.UUID, name, keyPrefix, keyHash string, scopes []string, createdBy uuid.UUID, expiresAt *time.Time) (APIKey, error)

	// GetAPIKeyByPrefix looks up a key by its lookup prefix. Returns
	// ErrNotFound when absent.
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (APIKey, error)

	// TouchLastUsed sets last_used_at unconditionally to at. Throttling to
	// LastUsedThrottle is enforced by TouchLastUsed (the package function
	// below), not by the store.
	TouchLastUsed(ctx context.Context, id uuid.UUID, at time.Time) error
}

// ValidateScopes rejects an empty scope list and any scope matching a
// forbidden prefix or exact code. Order of scopes is preserved; duplicates
// are not deduplicated (callers rarely send them and the wire contract
// treats scopes as an opaque set for permission checks).
func ValidateScopes(scopes []string) error {
	if len(scopes) == 0 {
		return ErrEmptyScopes
	}
	for _, s := range scopes {
		if ForbiddenScopeExact[s] {
			return ErrForbiddenScope
		}
		for _, prefix := range ForbiddenScopePrefixes {
			if strings.HasPrefix(s, prefix) {
				return ErrForbiddenScope
			}
		}
	}
	return nil
}

// randomString returns a cryptographically random string of length n drawn
// from randomAlphabet.
func randomString(n int) (string, error) {
	b := make([]byte, n)
	max := big.NewInt(int64(len(randomAlphabet)))
	for i := range b {
		idx, err := rand.Int(rand.Reader, max)
		if err != nil {
			return "", err
		}
		b[i] = randomAlphabet[idx.Int64()]
	}
	return string(b), nil
}

// GenerateRawKey creates a fresh (prefix, secret, raw) triple. raw is the
// full wire token "ak_<prefix>_<secret>"; prefix is stored verbatim for
// lookup; secret is never persisted (only its bcrypt hash is).
func GenerateRawKey() (prefix, secret, raw string, err error) {
	prefix, err = randomString(KeyPrefixLen)
	if err != nil {
		return "", "", "", err
	}
	secret, err = randomString(KeySecretLen)
	if err != nil {
		return "", "", "", err
	}
	raw = KeyWirePrefix + prefix + "_" + secret
	return prefix, secret, raw, nil
}

// ParseRawKey splits a raw wire token into its prefix and secret segments.
// Returns ErrMalformed if raw does not match ak_<prefix12>_<secret43>.
func ParseRawKey(raw string) (prefix, secret string, err error) {
	if !strings.HasPrefix(raw, KeyWirePrefix) {
		return "", "", ErrMalformed
	}
	rest := strings.TrimPrefix(raw, KeyWirePrefix)
	parts := strings.SplitN(rest, "_", 2)
	if len(parts) != 2 {
		return "", "", ErrMalformed
	}
	prefix, secret = parts[0], parts[1]
	if len(prefix) != KeyPrefixLen || len(secret) != KeySecretLen {
		return "", "", ErrMalformed
	}
	return prefix, secret, nil
}

// IssueInput carries the fields needed to mint a new key.
type IssueInput struct {
	OrgID     uuid.UUID
	ChannelID *uuid.UUID // optional
	Name      string
	Scopes    []string
	CreatedBy uuid.UUID
	ExpiresAt *time.Time // optional
}

// Issue validates scopes, generates a fresh key, hashes its secret and
// persists the row via store. It returns the stored APIKey (KeyHash
// populated, never the secret) and the raw wire token — the ONLY place the
// raw token is ever available; callers must return it to the requester
// immediately and never log or persist it themselves.
func Issue(ctx context.Context, store Store, in IssueInput) (APIKey, string, error) {
	if strings.TrimSpace(in.Name) == "" {
		return APIKey{}, "", ErrNameRequired
	}
	if err := ValidateScopes(in.Scopes); err != nil {
		return APIKey{}, "", err
	}
	prefix, secret, raw, err := GenerateRawKey()
	if err != nil {
		return APIKey{}, "", err
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(secret), BcryptCost)
	if err != nil {
		return APIKey{}, "", err
	}
	key, err := store.InsertAPIKey(ctx, in.OrgID, in.ChannelID, in.Name, prefix, string(hash), in.Scopes, in.CreatedBy, in.ExpiresAt)
	if err != nil {
		return APIKey{}, "", err
	}
	return key, raw, nil
}

// Authenticate looks up raw's prefix, verifies the secret against the
// stored bcrypt hash, and checks revoked_at/expires_at. now is injected so
// callers can use a clock.Clock for deterministic tests.
//
// Returns (key, nil) only when the key is structurally valid, the secret
// matches, and the key is neither revoked nor expired. Callers are
// responsible for calling TouchLastUsed on success and for mapping the
// returned key's Scopes into an auth.Actor with Type=service (spec §13.1).
func Authenticate(ctx context.Context, store Store, raw string, now time.Time) (APIKey, error) {
	prefix, secret, err := ParseRawKey(raw)
	if err != nil {
		return APIKey{}, err
	}
	key, err := store.GetAPIKeyByPrefix(ctx, prefix)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return APIKey{}, ErrNotFound
		}
		return APIKey{}, err
	}
	if bcrypt.CompareHashAndPassword([]byte(key.KeyHash), []byte(secret)) != nil {
		return APIKey{}, ErrSecretMismatch
	}
	if key.IsRevoked() {
		return APIKey{}, ErrRevoked
	}
	if key.IsExpired(now) {
		return APIKey{}, ErrExpired
	}
	return key, nil
}

// TouchLastUsed updates key's last_used_at to now, but only if it has never
// been set or more than LastUsedThrottle has elapsed since the last write
// (spec §13.1: "не чаще раза в минуту"). Returns false, nil when the touch
// was skipped because it is within the throttle window.
func TouchLastUsed(ctx context.Context, store Store, key APIKey, now time.Time) (bool, error) {
	if key.LastUsedAt != nil && now.Sub(*key.LastUsedAt) < LastUsedThrottle {
		return false, nil
	}
	if err := store.TouchLastUsed(ctx, key.ID, now); err != nil {
		return false, err
	}
	return true, nil
}
