/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns HTTP 200 unconditionally while the process is alive and able to
         *     serve HTTP. Bound to the Docker HEALTHCHECK directive via arena-healthcheck
         *     binary. Kubernetes liveness probes should point here.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Iterates all registered ReadinessProbes (database, Redis, etc.) and
         *     aggregates their results. Returns 200 when every probe passes or when no
         *     probes are registered (e.g. fresh server). Returns 503 with a "checks"
         *     map indicating which probes failed and why.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics scrape endpoint
         * @description Exposes arena_http_request_duration_seconds histograms, arena_http_requests_total
         *     counters, database pool gauges, worker job lag, and outbox backlog for
         *     Prometheus scraping. This endpoint is only mounted when the server is started
         *     with a MetricsHandler (i.e. PROMETHEUS_ENABLED=true). Network-level access
         *     restriction (Prometheus scraper VLAN only) is enforced by the Dokploy reverse proxy.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service metadata + database check
         * @description Returns static service metadata (name, version, commit, supported locales)
         *     and the running PostgreSQL server_version + now() from a live SELECT.
         *     No authentication required. The database fields (db_version, db_now) are
         *     omitted when the database query fails — the endpoint still returns 200 with
         *     the static metadata so callers can distinguish "API alive" from "DB alive".
         */
        get: operations["getV1Info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info-slow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slow service metadata (graceful-shutdown test endpoint)
         * @description Identical to GET /v1/info but sleeps for a configurable delay (default 5s)
         *     before responding. Used exclusively in integration tests to verify that
         *     in-flight requests complete during a graceful shutdown (SIGTERM). The
         *     endpoint is always mounted (not gated by ENABLE_DEV_AUTH) so it is
         *     reachable without credentials during graceful-shutdown test scenarios.
         *     Must not be relied upon in production workloads.
         */
        get: operations["getV1InfoSlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dev/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a development JWT (dev-only)
         * @description Issues a signed HS256 JWT using the StubProvider. Only mounted when
         *     ENABLE_DEV_AUTH=true. Must never be reachable in production (config.Validate
         *     enforces that EnableStubAuth is false in production). The token can be used
         *     in "Authorization: Bearer <token>" headers to authenticate subsequent requests.
         */
        post: operations["postV1DevToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dev/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a development JWT via jwt/v5 issuer (dev-only)
         * @description Issues a signed HS256 JWT using the jwt/v5-backed IssueJWT function
         *     (AuthContext boundary PLACEHOLDER — feature #96). Only mounted when
         *     ENABLE_DEV_AUTH=true. Must never be reachable in production.
         *     The resulting token is accepted by the ValidateJWT middleware and
         *     populates an AuthContext (ActorID, OrgID, Roles, TokenID) in the
         *     request context.
         */
        post: operations["postV1DevAuthToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/echo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transactional echo command
         * @description Example transactional command that exercises the full cross-cutting boundary
         *     stack in a single PostgreSQL transaction:
         *       1. Auth boundary  — verifies Bearer JWT (401 if missing/invalid)
         *       2. Idempotency    — deduplicates by Idempotency-Key header; replays cached response
         *       3. Audit boundary — writes audit_events row in the same TX
         *       4. Outbox         — writes outbox_events row in the same TX (worker picks it up later)
         *
         *     On success returns the echoed message, actor ID, and the outbox event UUID.
         *     On retry with the same Idempotency-Key the middleware returns the original
         *     cached response without re-running the handler.
         */
        post: operations["postV1Echo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /**
                 * @description Machine-readable error code in dotted-namespace format
                 *     (e.g. "http.not_found", "auth.token_expired", "echo.invalid_body").
                 *     Always lowercase; namespace component followed by dot-separated sub-codes.
                 * @example auth.token_expired
                 */
                code: string;
                /**
                 * @description Human-readable error description (may be localised)
                 * @example authentication required
                 */
                message: string;
                /**
                 * @description Per-request correlation ID (also in X-Request-Id response header)
                 * @example 01J3K8MNTB4KXYZQR5V6W7SHJ2
                 */
                request_id: string;
                /**
                 * @description Distributed trace ID (also in X-Trace-Id response header)
                 * @example 4bf92f3577b34da6a3ce929d0e0e4736
                 */
                trace_id: string;
                /**
                 * @description Optional structured details about the error (analogous to a JSONB object).
                 *     May contain field-level validation errors, conflict context, or other
                 *     machine-readable diagnostic data. Omitted when there are no additional
                 *     details.
                 * @example {
                 *       "field": "message",
                 *       "reason": "must not be empty"
                 *     }
                 */
                details?: {
                    [key: string]: unknown;
                } | null;
            };
        };
        HealthzResponse: {
            /**
             * @description Always "ok" when the process is alive
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
        ReadyzResponse: {
            /**
             * @description "ready" when all probes pass, "not_ready" when any probe fails
             * @example ready
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /**
             * @description Map of probe name to status string ("ok" or error message)
             * @example {
             *       "database": "ok"
             *     }
             */
            checks: {
                [key: string]: string;
            };
        };
        InfoResponse: {
            /**
             * @description Application name
             * @example arena-api
             */
            app: string;
            /**
             * @description Semantic version string
             * @example 0.1.0
             */
            version: string;
            /**
             * @description Git commit SHA (short or full)
             * @example a1b2c3d
             */
            commit: string;
            /**
             * @description Deployment environment (development, staging, production)
             * @example development
             */
            env: string;
            /**
             * @description BCP-47 locale tags the server will accept
             * @example [
             *       "ru",
             *       "en"
             *     ]
             */
            supported_locales: string[];
            /**
             * @description Fallback locale when Accept-Language negotiation yields no match
             * @example en
             */
            default_locale: string;
            /**
             * @description Locale resolved for this specific request via Accept-Language → ?lang= → default_locale negotiation
             * @example en
             */
            active_locale: string;
            /**
             * Format: date-time
             * @description Current UTC wall clock time on the server (RFC3339Nano)
             * @example 2026-06-22T05:00:00.000000000Z
             */
            server_time: string;
            /**
             * @description PostgreSQL server_version string (omitted when DB query fails)
             * @example 17.0
             */
            db_version?: string;
            /**
             * Format: date-time
             * @description PostgreSQL now() at the time of the SELECT (omitted when DB query fails)
             * @example 2026-06-22T05:00:00.000000000Z
             */
            db_now?: string;
            /**
             * @description Per-request correlation ID
             * @example 01J3K8MNTB4KXYZQR5V6W7SHJ2
             */
            request_id: string;
            /**
             * @description Distributed trace ID
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id: string;
        };
        DevTokenRequest: {
            /**
             * @description UUIDv7 or any string identifier for the test actor. Defaults to "00000000-0000-0000-0000-000000000001".
             * @example 00000000-0000-0000-0000-000000000001
             */
            actor_id?: string;
            /**
             * @description Actor type label embedded in the JWT claims. Defaults to "stub_user".
             * @example stub_user
             */
            actor_type?: string;
            /**
             * @description Role list embedded in the JWT claims.
             * @example [
             *       "admin"
             *     ]
             */
            roles?: string[];
            /**
             * @description Token time-to-live in seconds. Defaults to 3600.
             * @example 3600
             */
            ttl_seconds?: number;
            /**
             * @description JWT audience claim. Defaults to the server's configured audience.
             * @example arena-api
             */
            audience?: string;
        };
        DevTokenResponse: {
            /**
             * @description Signed JWT (HS256) that can be used in Authorization headers
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token: string;
            /**
             * Format: date-time
             * @description Token expiry time (RFC3339)
             * @example 2026-06-22T06:00:00Z
             */
            expires_at: string;
            /**
             * @description Actor ID embedded in the token
             * @example 00000000-0000-0000-0000-000000000001
             */
            actor_id: string;
            /**
             * @description Actor type embedded in the token
             * @example stub_user
             */
            actor_type: string;
            /**
             * @description JWT issuer (iss) claim
             * @example arena-stub
             */
            issuer: string;
            /**
             * @description JWT audience (aud) claim
             * @example arena-api
             */
            audience: string;
        };
        DevAuthTokenRequest: {
            /**
             * Format: uuid
             * @description UUID to embed as the "sub" (subject) claim. Defaults to 00000000-0000-0000-0000-000000000001.
             * @example 00000000-0000-0000-0000-000000000042
             */
            actor_id?: string;
            /**
             * @description Optional organisation UUID embedded as the "org_id" claim.
             * @example 11111111-1111-1111-1111-111111111111
             */
            org_id?: string | null;
            /**
             * @description Coarse-grained role labels embedded in the "roles" claim.
             * @example [
             *       "admin",
             *       "viewer"
             *     ]
             */
            roles?: string[];
            /**
             * @description Token lifetime in seconds. Defaults to 3600 (1 hour) when omitted or ≤ 0.
             * @example 3600
             */
            ttl_seconds?: number;
        };
        DevAuthTokenResponse: {
            /**
             * @description Signed JWT (HS256 via jwt/v5) usable in Authorization Bearer headers.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token: string;
            /**
             * Format: date-time
             * @description Token expiry time (RFC3339 UTC).
             * @example 2026-06-22T07:00:00Z
             */
            expires_at: string;
            /**
             * @description The actor UUID embedded in the token's sub claim.
             * @example 00000000-0000-0000-0000-000000000042
             */
            actor_id: string;
            /**
             * @description The iss claim value (configured JWT_ISSUER).
             * @example arena-dev
             */
            issuer: string;
            /**
             * @description The aud claim value (configured JWT_AUDIENCE).
             * @example arena-api
             */
            audience: string;
        };
        /**
         * @description Strict schema — the server rejects any field not defined here with
         *     HTTP 400 code='validation.unknown_field'. This protects against
         *     typos (e.g. "messsage" instead of "message") and forward-compat
         *     issues where clients inadvertently include private data in unknown
         *     fields.
         */
        EchoRequest: {
            /**
             * @description Message to echo. Must be non-empty. Maximum 8 KiB.
             * @example hello arena
             */
            message: string;
        };
        EchoResponse: {
            /**
             * @description The echoed message from the request body
             * @example hello arena
             */
            message: string;
            /**
             * @description ID of the authenticated actor who sent the request
             * @example 00000000-0000-0000-0000-000000000001
             */
            actor_id: string;
            /**
             * @description Per-request correlation ID
             * @example 01J3K8MNTB4KXYZQR5V6W7SHJ2
             */
            request_id: string;
            /**
             * @description Distributed trace ID
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id: string;
            /**
             * Format: uuid
             * @description UUIDv7 of the outbox_events row created for this echo (for downstream tracing)
             * @example 01929d0e-0e47-7000-8000-000000000001
             */
            echo_event_id: string;
            /**
             * @description The Idempotency-Key header value that was used to deduplicate this request
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            idempotent_key: string;
            /**
             * Format: date-time
             * @description Server-side timestamp when the response was built (RFC3339Nano)
             * @example 2026-06-22T05:00:00.000000000Z
             */
            issued_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All registered probes healthy (or no probes registered) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ready",
                     *       "checks": {
                     *         "database": "ok"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
            /** @description One or more probes failed — service should not receive traffic */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "not_ready",
                     *       "checks": {
                     *         "database": "connection refused"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text format metrics (text/plain; version=0.0.4) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # HELP arena_http_request_duration_seconds HTTP request latency in seconds
                     *     # TYPE arena_http_request_duration_seconds histogram
                     *     arena_http_request_duration_seconds_bucket{method="GET",route="/v1/info",status="200",le="0.005"} 1
                     */
                    "text/plain": string;
                };
            };
        };
    };
    getV1Info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service info (DB fields present when database query succeeds) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
            /** @description Internal server error — unexpected failure in request processing */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getV1InfoSlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service info (same schema as GET /v1/info, returned after the delay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    postV1DevToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DevTokenRequest"];
            };
        };
        responses: {
            /** @description Token issued successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevTokenResponse"];
                };
            };
            /** @description Request body is not valid JSON, or token mint failed (e.g. invalid TTL) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Dev auth is disabled (ENABLE_DEV_AUTH=false or stub not initialised) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    postV1DevAuthToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DevAuthTokenRequest"];
            };
        };
        responses: {
            /** @description Token issued successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevAuthTokenResponse"];
                };
            };
            /** @description Request body is not valid JSON, or actor_id / org_id is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Dev auth is disabled (ENABLE_DEV_AUTH=false) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    postV1Echo: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated UUID that uniquely identifies this mutation request.
                 *     Replays (same actor + same key) return the originally cached response
                 *     without re-executing the handler. TTL is 24 hours.
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EchoRequest"];
            };
        };
        responses: {
            /** @description Echo response (original or cached replay for duplicate Idempotency-Key) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EchoResponse"];
                };
            };
            /** @description Request body missing, not valid JSON, or "message" field is empty */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authorization header missing or JWT verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Idempotency-Key conflict — a different request body was submitted with the same key by the same actor */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request body exceeds 8 KiB limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Content-Type is not application/json */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal server error (DB unavailable, audit failure, idempotency failure, or commit failure) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Echo dependencies not wired (pool, audit, or idempotency store missing) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}

// ──────────────────────────────────────────────────────────────────────────────
// Named type aliases — shorthand for components["schemas"]["..."]
// Import directly instead of drilling into the components namespace:
//   import type { EchoRequest, EchoResponse, ErrorEnvelope } from "./index.d.ts";
// ──────────────────────────────────────────────────────────────────────────────

/** Structured error response envelope returned by all 4xx/5xx responses. */
export type ErrorEnvelope = components["schemas"]["ErrorEnvelope"];

export type HealthzResponse = components["schemas"]["HealthzResponse"];
export type ReadyzResponse = components["schemas"]["ReadyzResponse"];
export type InfoResponse = components["schemas"]["InfoResponse"];

/** Request body for POST /v1/echo */
export type EchoRequest = components["schemas"]["EchoRequest"];
/** Successful response body for POST /v1/echo (200 OK) */
export type EchoResponse = components["schemas"]["EchoResponse"];

export type DevTokenRequest    = components["schemas"]["DevTokenRequest"];
export type DevTokenResponse   = components["schemas"]["DevTokenResponse"];
export type DevAuthTokenRequest  = components["schemas"]["DevAuthTokenRequest"];
export type DevAuthTokenResponse = components["schemas"]["DevAuthTokenResponse"];

/** Pagination metadata for list endpoints. */
export type PaginationMeta = components["schemas"]["PaginationMeta"];

// ──────────────────────────────────────────────────────────────────────────────
// Error code string-literal union types.
//
// All Arena API error codes follow the dotted-namespace pattern:
//   "<namespace>.<sub_code>"  (e.g. "auth.token_expired")
// These union types enable exhaustive switch/case and IDE autocomplete on
// the ErrorEnvelope.error.code field returned by 4xx/5xx responses.
// ──────────────────────────────────────────────────────────────────────────────

/** HTTP-layer error codes (routing, content negotiation, body size limits). */
export type HttpErrorCode =
    | "http.not_found"
    | "http.method_not_allowed"
    | "http.payload_too_large"
    | "http.unsupported_media_type"
    | "http.bad_request";

/** Authentication and authorisation error codes. */
export type AuthErrorCode =
    | "auth.token_missing"
    | "auth.token_expired"
    | "auth.token_invalid"
    | "auth.token_malformed";

/** Echo endpoint business-logic error codes. */
export type EchoErrorCode =
    | "echo.invalid_body"
    | "echo.message_required";

/** External dependency error codes (database, cache, downstream services). */
export type DependencyErrorCode =
    | "dependency.database_unavailable";

/** Internal server error codes (unexpected / unhandled failures). */
export type InternalErrorCode =
    | "internal.unexpected";

/**
 * Union of all known Arena API error codes.
 * Use this type when writing client-side error handlers that need to cover
 * every possible code the server can return.
 *
 * @example
 *   function handleError(code: ApiErrorCode) {
 *     switch (code) {
 *       case "auth.token_expired":  return refreshToken();
 *       case "http.payload_too_large": return showFileTooLargeError();
 *       // ...
 *     }
 *   }
 */
export type ApiErrorCode =
    | HttpErrorCode
    | AuthErrorCode
    | EchoErrorCode
    | DependencyErrorCode
    | InternalErrorCode;
