// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for HealthzResponseStatus.
const (
	Ok HealthzResponseStatus = "ok"
)

// Defines values for NetworkAgentsListResponseAssignmentKind.
const (
	NetworkAgentsListResponseAssignmentKindAgent NetworkAgentsListResponseAssignmentKind = "agent"
)

// Defines values for NetworkOrganizationAssignmentAssignmentKind.
const (
	NetworkOrganizationAssignmentAssignmentKindAgent     NetworkOrganizationAssignmentAssignmentKind = "agent"
	NetworkOrganizationAssignmentAssignmentKindOrganizer NetworkOrganizationAssignmentAssignmentKind = "organizer"
)

// Defines values for NetworkOrganizationAssignmentStatus.
const (
	NetworkOrganizationAssignmentStatusActive  NetworkOrganizationAssignmentStatus = "active"
	NetworkOrganizationAssignmentStatusRevoked NetworkOrganizationAssignmentStatus = "revoked"
)

// Defines values for NetworkOrganizersListResponseAssignmentKind.
const (
	Organizer NetworkOrganizersListResponseAssignmentKind = "organizer"
)

// Defines values for NetworkUserAssignmentStatus.
const (
	NetworkUserAssignmentStatusActive  NetworkUserAssignmentStatus = "active"
	NetworkUserAssignmentStatusRevoked NetworkUserAssignmentStatus = "revoked"
)

// Defines values for OperatorNetworkStatus.
const (
	Active   OperatorNetworkStatus = "active"
	Archived OperatorNetworkStatus = "archived"
)

// Defines values for ReadyzResponseStatus.
const (
	NotReady ReadyzResponseStatus = "not_ready"
	Ready    ReadyzResponseStatus = "ready"
)

// AssignNetworkUserRequest defines model for AssignNetworkUserRequest.
type AssignNetworkUserRequest struct {
	// UserId UUID of the user to attach to the network
	UserId openapi_types.UUID `json:"user_id"`
}

// AttachNetworkOrganizationRequest defines model for AttachNetworkOrganizationRequest.
type AttachNetworkOrganizationRequest struct {
	// OrganizationId UUID of the organization to attach
	OrganizationId openapi_types.UUID `json:"organization_id"`
}

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	// Email User's registered email address
	Email openapi_types.Email `json:"email"`

	// Password Plain-text password for verification
	Password string `json:"password"`
}

// AuthLoginResponse defines model for AuthLoginResponse.
type AuthLoginResponse struct {
	// AccessToken Short-lived HS256 JWT access token (15-minute TTL)
	AccessToken string `json:"access_token"`

	// ExpiresAt RFC 3339 expiry timestamp of the access token
	ExpiresAt time.Time `json:"expires_at"`

	// RefreshToken Long-lived opaque refresh token (30-day TTL); store securely
	RefreshToken string `json:"refresh_token"`

	// TokenType Token type — always "Bearer"
	TokenType string `json:"token_type"`

	// UserId UUIDv7 of the authenticated user
	UserId openapi_types.UUID `json:"user_id"`
}

// AuthLogoutRequest defines model for AuthLogoutRequest.
type AuthLogoutRequest struct {
	// RefreshToken Opaque refresh token to revoke (issued by POST /v1/auth/login)
	RefreshToken string `json:"refresh_token"`
}

// AuthRefreshRequest defines model for AuthRefreshRequest.
type AuthRefreshRequest struct {
	// RefreshToken Opaque refresh token issued by POST /v1/auth/login
	RefreshToken string `json:"refresh_token"`
}

// AuthRefreshResponse defines model for AuthRefreshResponse.
type AuthRefreshResponse struct {
	// AccessToken New short-lived HS256 JWT access token (15-minute TTL)
	AccessToken string `json:"access_token"`

	// ExpiresAt RFC 3339 expiry timestamp of the new access token
	ExpiresAt time.Time `json:"expires_at"`

	// TokenType Token type — always "Bearer"
	TokenType string `json:"token_type"`

	// UserId UUIDv7 of the authenticated user
	UserId openapi_types.UUID `json:"user_id"`
}

// AuthRegisterRequest defines model for AuthRegisterRequest.
type AuthRegisterRequest struct {
	// Email User's email address (normalised to lowercase before storage)
	Email openapi_types.Email `json:"email"`

	// Password Plain-text password (bcrypt-hashed server-side; 8–72 chars)
	Password string `json:"password"`
}

// AuthRegisterResponse defines model for AuthRegisterResponse.
type AuthRegisterResponse struct {
	// CreatedAt ISO 8601 / RFC 3339 timestamp of account creation
	CreatedAt time.Time `json:"created_at"`

	// Email Normalised email address stored in the DB
	Email openapi_types.Email `json:"email"`

	// Message Human-readable confirmation message
	Message string `json:"message"`

	// UserId UUIDv7 of the newly created user
	UserId openapi_types.UUID `json:"user_id"`
}

// AuthVerifyResponse defines model for AuthVerifyResponse.
type AuthVerifyResponse struct {
	// Email Verified email address
	Email openapi_types.Email `json:"email"`

	// EmailVerifiedAt ISO 8601 / RFC 3339 timestamp of verification
	EmailVerifiedAt time.Time `json:"email_verified_at"`

	// Message Human-readable confirmation message
	Message string `json:"message"`

	// UserId UUIDv7 of the verified user
	UserId openapi_types.UUID `json:"user_id"`
}

// CreateOperatorNetworkRequest defines model for CreateOperatorNetworkRequest.
type CreateOperatorNetworkRequest struct {
	// Name Human-readable network name (trimmed server-side)
	Name string `json:"name"`

	// Slug URL-safe slug. Lower-cased and trimmed server-side before validation.
	// Must satisfy the regex CHECK constraint from migration
	// 0043_operator_networks.sql.
	Slug string `json:"slug"`
}

// CreateOrganizationRequest Request body for POST /v1/organizations.
type CreateOrganizationRequest struct {
	// Country ISO 3166-1 alpha-2 country code (optional)
	Country *string `json:"country,omitempty"`

	// DefaultLocale BCP 47 locale tag (optional; defaults to "en")
	DefaultLocale *string `json:"default_locale,omitempty"`

	// Name Human-readable display name (must be unique among active organizations)
	Name string `json:"name"`

	// ReservationTtlSeconds Seat-hold expiry window in seconds (optional; defaults to 1200)
	ReservationTtlSeconds *int `json:"reservation_ttl_seconds,omitempty"`

	// Slug URL-safe identifier (lowercase; must be unique among active organizations)
	Slug string `json:"slug"`
}

// DevAuthTokenRequest defines model for DevAuthTokenRequest.
type DevAuthTokenRequest struct {
	// ActorId UUID to embed as the "sub" (subject) claim. Defaults to 00000000-0000-0000-0000-000000000001.
	ActorId *openapi_types.UUID `json:"actor_id,omitempty"`

	// OrgId Optional organisation UUID embedded as the "org_id" claim.
	OrgId *openapi_types.UUID `json:"org_id,omitempty"`

	// Roles Coarse-grained role labels embedded in the "roles" claim.
	Roles *[]string `json:"roles,omitempty"`

	// TtlSeconds Token lifetime in seconds. Defaults to 3600 (1 hour) when omitted or ≤ 0.
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// DevAuthTokenResponse defines model for DevAuthTokenResponse.
type DevAuthTokenResponse struct {
	// ActorId The actor UUID embedded in the token's sub claim.
	ActorId string `json:"actor_id"`

	// Audience The aud claim value (configured JWT_AUDIENCE).
	Audience string `json:"audience"`

	// ExpiresAt Token expiry time (RFC3339 UTC).
	ExpiresAt time.Time `json:"expires_at"`

	// Issuer The iss claim value (configured JWT_ISSUER).
	Issuer string `json:"issuer"`

	// Token Signed JWT (HS256 via jwt/v5) usable in Authorization Bearer headers.
	Token string `json:"token"`
}

// DevTokenRequest defines model for DevTokenRequest.
type DevTokenRequest struct {
	// ActorId UUIDv7 or any string identifier for the test actor. Defaults to "00000000-0000-0000-0000-000000000001".
	ActorId *string `json:"actor_id,omitempty"`

	// ActorType Actor type label embedded in the JWT claims. Defaults to "stub_user".
	ActorType *string `json:"actor_type,omitempty"`

	// Audience JWT audience claim. Defaults to the server's configured audience.
	Audience *string `json:"audience,omitempty"`

	// Roles Role list embedded in the JWT claims.
	Roles *[]string `json:"roles,omitempty"`

	// TtlSeconds Token time-to-live in seconds. Defaults to 3600.
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// DevTokenResponse defines model for DevTokenResponse.
type DevTokenResponse struct {
	// ActorId Actor ID embedded in the token
	ActorId string `json:"actor_id"`

	// ActorType Actor type embedded in the token
	ActorType string `json:"actor_type"`

	// Audience JWT audience (aud) claim
	Audience string `json:"audience"`

	// ExpiresAt Token expiry time (RFC3339)
	ExpiresAt time.Time `json:"expires_at"`

	// Issuer JWT issuer (iss) claim
	Issuer string `json:"issuer"`

	// Token Signed JWT (HS256) that can be used in Authorization headers
	Token string `json:"token"`
}

// EchoRequest Strict schema — the server rejects any field not defined here with
// HTTP 400 code='validation.unknown_field'. This protects against
// typos (e.g. "messsage" instead of "message") and forward-compat
// issues where clients inadvertently include private data in unknown
// fields.
type EchoRequest struct {
	// Message Message to echo. Must be non-empty. Maximum 8 KiB.
	Message string `json:"message"`
}

// EchoResponse defines model for EchoResponse.
type EchoResponse struct {
	// ActorId ID of the authenticated actor who sent the request
	ActorId string `json:"actor_id"`

	// EchoEventId UUIDv7 of the outbox_events row created for this echo (for downstream tracing)
	EchoEventId openapi_types.UUID `json:"echo_event_id"`

	// IdempotentKey The Idempotency-Key header value that was used to deduplicate this request
	IdempotentKey string `json:"idempotent_key"`

	// IssuedAt Server-side timestamp when the response was built (RFC3339Nano)
	IssuedAt time.Time `json:"issued_at"`

	// Message The echoed message from the request body
	Message string `json:"message"`

	// RequestId Per-request correlation ID
	RequestId string `json:"request_id"`

	// TraceId Distributed trace ID
	TraceId string `json:"trace_id"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	// Error Error details object containing machine-readable code, human-readable message, and correlation IDs.
	Error struct {
		// Code Machine-readable error code in dotted-namespace format
		// (e.g. "http.not_found", "auth.token_expired", "echo.invalid_body").
		// Always lowercase; namespace component followed by dot-separated sub-codes.
		Code string `json:"code"`

		// Details Optional structured details about the error (analogous to a JSONB object).
		// May contain field-level validation errors, conflict context, or other
		// machine-readable diagnostic data. Omitted when there are no additional
		// details.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Human-readable error description (may be localised)
		Message string `json:"message"`

		// RequestId Per-request correlation ID (also in X-Request-Id response header)
		RequestId string `json:"request_id"`

		// TraceId Distributed trace ID (also in X-Trace-Id response header)
		TraceId string `json:"trace_id"`
	} `json:"error"`
}

// GeoCitiesResponse defines model for GeoCitiesResponse.
type GeoCitiesResponse struct {
	// Cities Ordered list of reference cities with localised names
	Cities []GeoCityItem `json:"cities"`

	// Meta Standard pagination metadata returned by list endpoints.
	// Clients use this object to implement "load more" buttons or
	// paginator UI components. All fields are always present in list responses.
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// GeoCityItem defines model for GeoCityItem.
type GeoCityItem struct {
	// CountryId FK to countries.id
	CountryId openapi_types.UUID `json:"country_id"`

	// CountryIso2 ISO 3166-1 alpha-2 code of the parent country
	CountryIso2 string `json:"country_iso2"`

	// Id UUIDv7 primary key
	Id openapi_types.UUID `json:"id"`

	// Name Localised display name (resolved from i18n_text)
	Name string `json:"name"`

	// Slug URL-safe slug
	Slug string `json:"slug"`
}

// GeoCityResponse defines model for GeoCityResponse.
type GeoCityResponse struct {
	// CountryId UUID of the parent country (FK → countries.id)
	CountryId openapi_types.UUID `json:"country_id"`

	// CreatedAt ISO 8601 / RFC 3339 timestamp of row creation
	CreatedAt time.Time `json:"created_at"`

	// Id UUIDv7 primary key of the city row
	Id openapi_types.UUID `json:"id"`

	// Slug URL-safe identifier slug
	Slug string `json:"slug"`
}

// GeoCountriesResponse defines model for GeoCountriesResponse.
type GeoCountriesResponse struct {
	// Countries Ordered list of reference countries with localised names
	Countries []GeoCountryItem `json:"countries"`

	// Meta Standard pagination metadata returned by list endpoints.
	// Clients use this object to implement "load more" buttons or
	// paginator UI components. All fields are always present in list responses.
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// GeoCountryItem defines model for GeoCountryItem.
type GeoCountryItem struct {
	// Id UUIDv7 primary key
	Id openapi_types.UUID `json:"id"`

	// Iso2 ISO 3166-1 alpha-2 code
	Iso2 string `json:"iso2"`

	// Iso3 ISO 3166-1 alpha-3 code
	Iso3 string `json:"iso3"`

	// Name Localised display name (resolved from i18n_text)
	Name string `json:"name"`

	// Slug URL-safe slug
	Slug string `json:"slug"`
}

// GeoCountryResponse defines model for GeoCountryResponse.
type GeoCountryResponse struct {
	// CreatedAt ISO 8601 / RFC 3339 timestamp of row creation
	CreatedAt time.Time `json:"created_at"`

	// Id UUIDv7 primary key of the country row
	Id openapi_types.UUID `json:"id"`

	// Iso2 ISO 3166-1 alpha-2 country code
	Iso2 string `json:"iso2"`

	// Iso3 ISO 3166-1 alpha-3 country code
	Iso3 string `json:"iso3"`

	// Slug URL-safe identifier slug
	Slug string `json:"slug"`
}

// GeoCreateCityRequest defines model for GeoCreateCityRequest.
type GeoCreateCityRequest struct {
	// CountryId UUID of the parent country
	CountryId openapi_types.UUID `json:"country_id"`

	// NameEn English localised name (seeded into i18n_text)
	NameEn *string `json:"name_en,omitempty"`

	// NameRu Russian localised name (seeded into i18n_text)
	NameRu *string `json:"name_ru,omitempty"`

	// Slug URL-safe slug
	Slug string `json:"slug"`
}

// GeoCreateCountryRequest defines model for GeoCreateCountryRequest.
type GeoCreateCountryRequest struct {
	// Iso2 ISO 3166-1 alpha-2 code (uppercase)
	Iso2 string `json:"iso2"`

	// Iso3 ISO 3166-1 alpha-3 code (uppercase)
	Iso3 string `json:"iso3"`

	// NameEn English localised name (seeded into i18n_text)
	NameEn *string `json:"name_en,omitempty"`

	// NameRu Russian localised name (seeded into i18n_text)
	NameRu *string `json:"name_ru,omitempty"`

	// Slug URL-safe slug
	Slug string `json:"slug"`
}

// GeoUpdateCityRequest defines model for GeoUpdateCityRequest.
type GeoUpdateCityRequest struct {
	// NameEn Updated English localised name
	NameEn *string `json:"name_en,omitempty"`

	// NameRu Updated Russian localised name
	NameRu *string `json:"name_ru,omitempty"`

	// Slug Updated URL-safe slug
	Slug *string `json:"slug,omitempty"`
}

// GeoUpdateCountryRequest defines model for GeoUpdateCountryRequest.
type GeoUpdateCountryRequest struct {
	// Iso3 Updated ISO 3166-1 alpha-3 code
	Iso3 *string `json:"iso3,omitempty"`

	// NameEn Updated English localised name
	NameEn *string `json:"name_en,omitempty"`

	// NameRu Updated Russian localised name
	NameRu *string `json:"name_ru,omitempty"`

	// Slug Updated URL-safe slug
	Slug *string `json:"slug,omitempty"`
}

// HealthzResponse defines model for HealthzResponse.
type HealthzResponse struct {
	// Status Always "ok" when the process is alive
	Status HealthzResponseStatus `json:"status"`
}

// HealthzResponseStatus Always "ok" when the process is alive
type HealthzResponseStatus string

// ImpersonateRequest defines model for ImpersonateRequest.
type ImpersonateRequest struct {
	// DurationSeconds Token lifetime in seconds. Capped at 1800 (30 minutes).
	// When absent or zero, defaults to 1800.
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// Reason Mandatory human-readable business justification for the impersonation.
	Reason string `json:"reason"`

	// UserId UUID of the target user to impersonate.
	UserId openapi_types.UUID `json:"user_id"`
}

// ImpersonateResponse defines model for ImpersonateResponse.
type ImpersonateResponse struct {
	// ExpiresAt Absolute UTC expiry time of the impersonation token (RFC 3339).
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// ImpersonatedBy UUID of the admin actor who issued this impersonation token.
	ImpersonatedBy *openapi_types.UUID `json:"impersonated_by,omitempty"`

	// ImpersonatedUserId UUID of the target user being impersonated.
	ImpersonatedUserId *openapi_types.UUID `json:"impersonated_user_id,omitempty"`

	// Reason Echoed-back business justification (as stored in audit_events).
	Reason *string `json:"reason,omitempty"`

	// Token Scoped impersonation bearer JWT. Use in Authorization header to act as the target user.
	Token *string `json:"token,omitempty"`
}

// InfoResponse defines model for InfoResponse.
type InfoResponse struct {
	// ActiveLocale Locale resolved for this specific request via Accept-Language → ?lang= → default_locale negotiation
	ActiveLocale string `json:"active_locale"`

	// App Application name
	App string `json:"app"`

	// Commit Git commit SHA (short or full)
	Commit string `json:"commit"`

	// DbNow PostgreSQL now() at the time of the SELECT (omitted when DB query fails)
	DbNow *time.Time `json:"db_now,omitempty"`

	// DbVersion PostgreSQL server_version string (omitted when DB query fails)
	DbVersion *string `json:"db_version,omitempty"`

	// DefaultLocale Fallback locale when Accept-Language negotiation yields no match
	DefaultLocale string `json:"default_locale"`

	// Env Deployment environment (development, staging, production)
	Env string `json:"env"`

	// RequestId Per-request correlation ID
	RequestId string `json:"request_id"`

	// ServerTime Current UTC wall clock time on the server (RFC3339Nano)
	ServerTime time.Time `json:"server_time"`

	// SupportedLocales BCP-47 locale tags the server will accept
	SupportedLocales []string `json:"supported_locales"`

	// TraceId Distributed trace ID
	TraceId string `json:"trace_id"`

	// Version Semantic version string
	Version string `json:"version"`
}

// MeAssignedNetwork defines model for MeAssignedNetwork.
type MeAssignedNetwork struct {
	// Id Operator network UUID
	Id string `json:"id"`

	// Name Human-readable operator network name
	Name string `json:"name"`

	// Slug URL-safe operator network slug
	Slug string `json:"slug"`

	// Status Operator network lifecycle status (active / suspended / archived)
	Status string `json:"status"`
}

// MeOrganizationMembership defines model for MeOrganizationMembership.
type MeOrganizationMembership struct {
	// Id Membership row UUID
	Id string `json:"id"`

	// JoinedAt When the membership was granted
	JoinedAt time.Time `json:"joined_at"`

	// OrgId Organization UUID
	OrgId string `json:"org_id"`

	// Role Role name held by the user inside the organization
	Role string `json:"role"`

	// Status Membership lifecycle status (always "active" in this response)
	Status string `json:"status"`
}

// MeResponse Snapshot of the authenticated user's context returned by GET /v1/me.
// Backwards-compatible: feature #211 added `assigned_networks` and
// `available_scopes`; clients that only consume the original blocks
// keep working without changes.
type MeResponse struct {
	// AssignedNetworks Operator networks the user belongs to (network_users.status='active').
	// Empty for users who are not part of any operator network.
	AssignedNetworks []MeAssignedNetwork `json:"assigned_networks"`

	// AvailableScopes Deterministically-ordered authorization scopes the caller can act
	// under. Order: "global" (bypass roles), "platform" (platform_operator),
	// sorted "network:<uuid>" entries, sorted "organization:<uuid>" entries.
	AvailableScopes []string `json:"available_scopes"`

	// OrganizationMemberships Every active organization membership held by the user
	OrganizationMemberships []MeOrganizationMembership `json:"organization_memberships"`

	// Permissions Flat list of permission names expanded from roles
	Permissions []string `json:"permissions"`

	// Roles Deduplicated union of JWT roles and active membership roles, sorted ascending
	Roles []string `json:"roles"`

	// User Authenticated user header block — identity claims extracted from the JWT
	User MeUser `json:"user"`
}

// MeUser defines model for MeUser.
type MeUser struct {
	// Id Actor ID from the JWT (typically a UUID)
	Id string `json:"id"`

	// ImpersonatedBy Admin actor ID that minted the impersonation token (omitted when empty)
	ImpersonatedBy *string `json:"impersonated_by,omitempty"`

	// ImpersonationReason Business justification recorded when the impersonation token was issued
	ImpersonationReason *string `json:"impersonation_reason,omitempty"`

	// IsImpersonated True when the token was issued via the impersonation flow (#167)
	IsImpersonated bool `json:"is_impersonated"`

	// Issuer JWT iss claim (omitted when empty)
	Issuer *string `json:"issuer,omitempty"`

	// Type Actor type — stub_user / user / service / anonymous
	Type string `json:"type"`
}

// NetworkAgentsListResponse defines model for NetworkAgentsListResponse.
type NetworkAgentsListResponse struct {
	// Agents Active agent attachments for the given operator network
	Agents []NetworkOrganizationAssignment `json:"agents"`

	// AssignmentKind Always "agent" on this endpoint
	AssignmentKind NetworkAgentsListResponseAssignmentKind `json:"assignment_kind"`

	// NetworkId Parent operator network UUID
	NetworkId openapi_types.UUID `json:"network_id"`

	// Total Number of active agent attachments returned
	Total int `json:"total"`
}

// NetworkAgentsListResponseAssignmentKind Always "agent" on this endpoint
type NetworkAgentsListResponseAssignmentKind string

// NetworkOrganizationAssignment A `network_organizations` row attaching an organization to an
// operator network as either an `organizer` or an `agent`.
type NetworkOrganizationAssignment struct {
	// AssignmentKind Role of the organization within the network
	AssignmentKind NetworkOrganizationAssignmentAssignmentKind `json:"assignment_kind"`

	// AttachedAt When the organization was first attached (RFC 3339)
	AttachedAt time.Time `json:"attached_at"`

	// CreatedAt Row creation timestamp (RFC 3339)
	CreatedAt time.Time `json:"created_at"`

	// Id UUIDv7 of the attachment row
	Id openapi_types.UUID `json:"id"`

	// NetworkId Parent operator_network UUID
	NetworkId openapi_types.UUID `json:"network_id"`

	// OrganizationId Attached organization UUID
	OrganizationId openapi_types.UUID `json:"organization_id"`

	// Status Lifecycle status of the attachment
	Status NetworkOrganizationAssignmentStatus `json:"status"`

	// UpdatedAt Last-modified timestamp (RFC 3339)
	UpdatedAt time.Time `json:"updated_at"`
}

// NetworkOrganizationAssignmentAssignmentKind Role of the organization within the network
type NetworkOrganizationAssignmentAssignmentKind string

// NetworkOrganizationAssignmentStatus Lifecycle status of the attachment
type NetworkOrganizationAssignmentStatus string

// NetworkOrganizationAttachResponse defines model for NetworkOrganizationAttachResponse.
type NetworkOrganizationAttachResponse struct {
	// NetworkOrganization A `network_organizations` row attaching an organization to an
	// operator network as either an `organizer` or an `agent`.
	NetworkOrganization NetworkOrganizationAssignment `json:"network_organization"`

	// Reactivated Present and true when the call re-activated a previously revoked
	// attachment (HTTP 200). Absent on a first-time insert (HTTP 201).
	Reactivated *bool `json:"reactivated,omitempty"`
}

// NetworkOrganizationDetachResponse defines model for NetworkOrganizationDetachResponse.
type NetworkOrganizationDetachResponse struct {
	// Detached Always true on success
	Detached bool `json:"detached"`

	// NetworkOrganization A `network_organizations` row attaching an organization to an
	// operator network as either an `organizer` or an `agent`.
	NetworkOrganization NetworkOrganizationAssignment `json:"network_organization"`
}

// NetworkOrganizersListResponse defines model for NetworkOrganizersListResponse.
type NetworkOrganizersListResponse struct {
	// AssignmentKind Always "organizer" on this endpoint
	AssignmentKind NetworkOrganizersListResponseAssignmentKind `json:"assignment_kind"`

	// NetworkId Parent operator network UUID
	NetworkId openapi_types.UUID `json:"network_id"`

	// Organizers Active organizer attachments for the given operator network
	Organizers []NetworkOrganizationAssignment `json:"organizers"`

	// Total Number of active organizer attachments returned
	Total int `json:"total"`
}

// NetworkOrganizersListResponseAssignmentKind Always "organizer" on this endpoint
type NetworkOrganizersListResponseAssignmentKind string

// NetworkUserAssignResponse defines model for NetworkUserAssignResponse.
type NetworkUserAssignResponse struct {
	// NetworkUser A `network_users` row binding a user to an operator network with a
	// role (default "network_operator") and a lifecycle status.
	NetworkUser NetworkUserAssignment `json:"network_user"`

	// Reactivated Present and true when the call re-activated a previously revoked
	// assignment (HTTP 200). Absent on a first-time insert (HTTP 201).
	Reactivated *bool `json:"reactivated,omitempty"`
}

// NetworkUserAssignment A `network_users` row binding a user to an operator network with a
// role (default "network_operator") and a lifecycle status.
type NetworkUserAssignment struct {
	// CreatedAt When the assignment was first created (RFC 3339)
	CreatedAt time.Time `json:"created_at"`

	// Id UUIDv7 of the assignment row
	Id openapi_types.UUID `json:"id"`

	// NetworkId Parent operator_network UUID
	NetworkId openapi_types.UUID `json:"network_id"`

	// Role Role granted by the assignment (currently always "network_operator")
	Role string `json:"role"`

	// Status Lifecycle status of the assignment
	Status NetworkUserAssignmentStatus `json:"status"`

	// UpdatedAt Last-modified timestamp (RFC 3339)
	UpdatedAt time.Time `json:"updated_at"`

	// UserId Assigned user UUID
	UserId openapi_types.UUID `json:"user_id"`
}

// NetworkUserAssignmentStatus Lifecycle status of the assignment
type NetworkUserAssignmentStatus string

// NetworkUserListResponse defines model for NetworkUserListResponse.
type NetworkUserListResponse struct {
	// NetworkId Parent operator network UUID
	NetworkId openapi_types.UUID `json:"network_id"`

	// NetworkUsers Active network-user assignments for the given operator network
	NetworkUsers []NetworkUserAssignment `json:"network_users"`

	// Total Number of active network user assignments returned
	Total int `json:"total"`
}

// NetworkUserRemoveResponse defines model for NetworkUserRemoveResponse.
type NetworkUserRemoveResponse struct {
	// NetworkUser A `network_users` row binding a user to an operator network with a
	// role (default "network_operator") and a lifecycle status.
	NetworkUser NetworkUserAssignment `json:"network_user"`

	// Removed Always true on success
	Removed bool `json:"removed"`
}

// OperatorNetwork An operator_network row (migration 0043_operator_networks.sql).
// Represents a platform-level grouping that overlays organizations: a
// `network_operator` user is assigned to one or more networks, and
// each network is in turn attached to organizations as either an
// `organizer` or an `agent` via network_organizations.
type OperatorNetwork struct {
	// ArchivedAt RFC 3339 archival timestamp; emitted as JSON `null` while the
	// operator network is still active. The OAS 3.1 type-array
	// idiom (`type: [string, "null"]`) is not yet supported by
	// oapi-codegen v2.4.1 (see CLAUDE.md), so nullability is
	// described in prose here and surfaced as `*time.Time` in the
	// sqlc layer / `*string` in the HTTP DTO (networks.go:61).
	ArchivedAt time.Time `json:"archived_at"`

	// CreatedAt Creation timestamp (RFC 3339)
	CreatedAt time.Time `json:"created_at"`

	// Id UUIDv7 of the operator network
	Id openapi_types.UUID `json:"id"`

	// Name Human-readable operator network name
	Name string `json:"name"`

	// Slug URL-safe slug, matches the CHECK constraint
	// `^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$` enforced by migration
	// 0043_operator_networks.sql.
	Slug string `json:"slug"`

	// Status Lifecycle status (active / archived)
	Status OperatorNetworkStatus `json:"status"`

	// UpdatedAt Last-modified timestamp (RFC 3339)
	UpdatedAt time.Time `json:"updated_at"`
}

// OperatorNetworkStatus Lifecycle status (active / archived)
type OperatorNetworkStatus string

// OperatorNetworkArchiveResponse defines model for OperatorNetworkArchiveResponse.
type OperatorNetworkArchiveResponse struct {
	// Archived Always true on success; included so callers can branch without inspecting `status`
	Archived bool `json:"archived"`

	// OperatorNetwork An operator_network row (migration 0043_operator_networks.sql).
	// Represents a platform-level grouping that overlays organizations: a
	// `network_operator` user is assigned to one or more networks, and
	// each network is in turn attached to organizations as either an
	// `organizer` or an `agent` via network_organizations.
	OperatorNetwork OperatorNetwork `json:"operator_network"`
}

// OperatorNetworkEnvelope defines model for OperatorNetworkEnvelope.
type OperatorNetworkEnvelope struct {
	// OperatorNetwork An operator_network row (migration 0043_operator_networks.sql).
	// Represents a platform-level grouping that overlays organizations: a
	// `network_operator` user is assigned to one or more networks, and
	// each network is in turn attached to organizations as either an
	// `organizer` or an `agent` via network_organizations.
	OperatorNetwork OperatorNetwork `json:"operator_network"`
}

// OperatorNetworkListResponse defines model for OperatorNetworkListResponse.
type OperatorNetworkListResponse struct {
	// OperatorNetworks Array of non-archived operator networks, ordered by `created_at` ascending
	OperatorNetworks []OperatorNetwork `json:"operator_networks"`

	// Total Number of operator networks returned (size of the array)
	Total int `json:"total"`
}

// OrganizationItem A single active organization (primary tenant boundary).
type OrganizationItem struct {
	// Country ISO 3166-1 alpha-2 country code or empty string
	Country string `json:"country"`

	// CreatedAt ISO 8601 / RFC 3339 timestamp of row creation
	CreatedAt time.Time `json:"created_at"`

	// DefaultLocale BCP 47 locale tag used as default for this organization
	DefaultLocale string `json:"default_locale"`

	// Id UUIDv7 primary key of the organization row
	Id openapi_types.UUID `json:"id"`

	// Name Human-readable display name (unique among active organizations)
	Name string `json:"name"`

	// ReservationTtlSeconds Seat-hold expiry window in seconds (default 1200 = 20 minutes)
	ReservationTtlSeconds int `json:"reservation_ttl_seconds"`

	// Slug URL-safe identifier (unique among active organizations, lowercase)
	Slug string `json:"slug"`

	// UpdatedAt ISO 8601 / RFC 3339 timestamp of last update
	UpdatedAt time.Time `json:"updated_at"`
}

// PaginationMeta Standard pagination metadata returned by list endpoints.
// Clients use this object to implement "load more" buttons or
// paginator UI components. All fields are always present in list responses.
type PaginationMeta struct {
	// Page Current page number (1-based; first page is 1)
	Page int `json:"page"`

	// PageSize Maximum number of items per page as requested by the caller
	PageSize int `json:"page_size"`

	// Total Total number of items that match the applied query filters
	Total int `json:"total"`

	// TotalPages Total number of pages computed as ceil(total / page_size)
	TotalPages int `json:"total_pages"`
}

// PasswordResetConfirmBody defines model for PasswordResetConfirmBody.
type PasswordResetConfirmBody struct {
	// NewPassword New plain-text password (bcrypt-hashed server-side; 8–72 chars)
	NewPassword string `json:"new_password"`

	// Token One-time reset token received in the password-reset email
	Token string `json:"token"`
}

// PasswordResetConfirmResponse defines model for PasswordResetConfirmResponse.
type PasswordResetConfirmResponse struct {
	// Message Confirmation message
	Message string `json:"message"`

	// UserId UUIDv7 of the user whose password was reset
	UserId openapi_types.UUID `json:"user_id"`
}

// PasswordResetRequestBody defines model for PasswordResetRequestBody.
type PasswordResetRequestBody struct {
	// Email Email address of the account for which a reset link is requested
	Email openapi_types.Email `json:"email"`
}

// PasswordResetRequestResponse defines model for PasswordResetRequestResponse.
type PasswordResetRequestResponse struct {
	// Message Informational message (same for found / not-found to prevent enumeration)
	Message string `json:"message"`
}

// ReadyzResponse defines model for ReadyzResponse.
type ReadyzResponse struct {
	// Checks Map of probe name to status string ("ok" or error message)
	Checks map[string]string `json:"checks"`

	// Status "ready" when all probes pass, "not_ready" when any probe fails
	Status ReadyzResponseStatus `json:"status"`
}

// ReadyzResponseStatus "ready" when all probes pass, "not_ready" when any probe fails
type ReadyzResponseStatus string

// ServerInfoResponse defines model for ServerInfoResponse.
type ServerInfoResponse struct {
	// BuildSha Git commit SHA embedded at build time via runtime/debug.ReadBuildInfo
	BuildSha string `json:"build_sha"`

	// Environment Deployment environment (development, staging, production)
	Environment string `json:"environment"`

	// Locales BCP-47 locale tags active on this server (ru, en)
	Locales []string `json:"locales"`

	// ServerTime Current UTC timestamp from the PostgreSQL server (via sqlc SelectServerTime)
	ServerTime time.Time `json:"server_time"`

	// Version Semantic version string from build metadata
	Version string `json:"version"`

	// WelcomeMessage Localised greeting resolved via Accept-Language → ?lang= → default negotiation
	WelcomeMessage string `json:"welcome_message"`
}

// UpdateOperatorNetworkRequest At least one of `name` or `slug` must be supplied. Empty strings are
// treated as "do not change". Slug is validated against the same regex
// as on create.
type UpdateOperatorNetworkRequest struct {
	// Name New human-readable network name (omit or empty to leave unchanged)
	Name *string `json:"name,omitempty"`

	// Slug New URL-safe slug (omit or empty to leave unchanged)
	Slug *string `json:"slug,omitempty"`
}

// UpdateOrganizationRequest Request body for PATCH /v1/organizations/{id}.
// All fields are optional — omitted or empty-string fields leave the
// existing value unchanged.
type UpdateOrganizationRequest struct {
	// Country New country code (optional; empty string leaves existing value)
	Country *string `json:"country,omitempty"`

	// DefaultLocale New default locale (optional; empty string leaves existing value)
	DefaultLocale *string `json:"default_locale,omitempty"`

	// Name New display name (optional; empty string leaves existing value)
	Name *string `json:"name,omitempty"`

	// ReservationTtlSeconds New TTL in seconds (optional; 0 leaves existing value)
	ReservationTtlSeconds *int `json:"reservation_ttl_seconds,omitempty"`

	// Slug New URL-safe slug (optional; empty string leaves existing value)
	Slug *string `json:"slug,omitempty"`
}

// GetV1AuthVerifyParams defines parameters for GetV1AuthVerify.
type GetV1AuthVerifyParams struct {
	// Token One-time verification token sent by email at registration
	Token string `form:"token" json:"token"`
}

// PostV1EchoParams defines parameters for PostV1Echo.
type PostV1EchoParams struct {
	// IdempotencyKey Client-generated UUID that uniquely identifies this mutation request.
	// Replays (same actor + same key) return the originally cached response
	// without re-executing the handler. TTL is 24 hours.
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// GetV1GeoCitiesParams defines parameters for GetV1GeoCities.
type GetV1GeoCitiesParams struct {
	// CountryId Filter cities by country UUID
	CountryId *openapi_types.UUID `form:"country_id,omitempty" json:"country_id,omitempty"`

	// Lang Preferred language code (e.g. "en", "ru"). Overrides Accept-Language.
	Lang *string `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetV1GeoCountriesParams defines parameters for GetV1GeoCountries.
type GetV1GeoCountriesParams struct {
	// Lang Preferred language code (e.g. "en", "ru"). Overrides Accept-Language.
	Lang *string `form:"lang,omitempty" json:"lang,omitempty"`
}

// PostV1AdminGeoCitiesJSONRequestBody defines body for PostV1AdminGeoCities for application/json ContentType.
type PostV1AdminGeoCitiesJSONRequestBody = GeoCreateCityRequest

// PatchV1AdminGeoCitiesIdJSONRequestBody defines body for PatchV1AdminGeoCitiesId for application/json ContentType.
type PatchV1AdminGeoCitiesIdJSONRequestBody = GeoUpdateCityRequest

// PostV1AdminGeoCountriesJSONRequestBody defines body for PostV1AdminGeoCountries for application/json ContentType.
type PostV1AdminGeoCountriesJSONRequestBody = GeoCreateCountryRequest

// PatchV1AdminGeoCountriesIso2JSONRequestBody defines body for PatchV1AdminGeoCountriesIso2 for application/json ContentType.
type PatchV1AdminGeoCountriesIso2JSONRequestBody = GeoUpdateCountryRequest

// PostV1AdminImpersonateJSONRequestBody defines body for PostV1AdminImpersonate for application/json ContentType.
type PostV1AdminImpersonateJSONRequestBody = ImpersonateRequest

// AttachNetworkAgentJSONRequestBody defines body for AttachNetworkAgent for application/json ContentType.
type AttachNetworkAgentJSONRequestBody = AttachNetworkOrganizationRequest

// AttachNetworkOrganizerJSONRequestBody defines body for AttachNetworkOrganizer for application/json ContentType.
type AttachNetworkOrganizerJSONRequestBody = AttachNetworkOrganizationRequest

// AssignNetworkUserJSONRequestBody defines body for AssignNetworkUser for application/json ContentType.
type AssignNetworkUserJSONRequestBody = AssignNetworkUserRequest

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody = AuthLoginRequest

// PostV1AuthLogoutJSONRequestBody defines body for PostV1AuthLogout for application/json ContentType.
type PostV1AuthLogoutJSONRequestBody = AuthLogoutRequest

// PostV1AuthPasswordResetConfirmJSONRequestBody defines body for PostV1AuthPasswordResetConfirm for application/json ContentType.
type PostV1AuthPasswordResetConfirmJSONRequestBody = PasswordResetConfirmBody

// PostV1AuthPasswordResetRequestJSONRequestBody defines body for PostV1AuthPasswordResetRequest for application/json ContentType.
type PostV1AuthPasswordResetRequestJSONRequestBody = PasswordResetRequestBody

// PostV1AuthRefreshJSONRequestBody defines body for PostV1AuthRefresh for application/json ContentType.
type PostV1AuthRefreshJSONRequestBody = AuthRefreshRequest

// PostV1AuthRegisterJSONRequestBody defines body for PostV1AuthRegister for application/json ContentType.
type PostV1AuthRegisterJSONRequestBody = AuthRegisterRequest

// PostV1DevAuthTokenJSONRequestBody defines body for PostV1DevAuthToken for application/json ContentType.
type PostV1DevAuthTokenJSONRequestBody = DevAuthTokenRequest

// PostV1DevTokenJSONRequestBody defines body for PostV1DevToken for application/json ContentType.
type PostV1DevTokenJSONRequestBody = DevTokenRequest

// PostV1EchoJSONRequestBody defines body for PostV1Echo for application/json ContentType.
type PostV1EchoJSONRequestBody = EchoRequest

// CreateOperatorNetworkJSONRequestBody defines body for CreateOperatorNetwork for application/json ContentType.
type CreateOperatorNetworkJSONRequestBody = CreateOperatorNetworkRequest

// UpdateOperatorNetworkJSONRequestBody defines body for UpdateOperatorNetwork for application/json ContentType.
type UpdateOperatorNetworkJSONRequestBody = UpdateOperatorNetworkRequest

// PostV1OrganizationsJSONRequestBody defines body for PostV1Organizations for application/json ContentType.
type PostV1OrganizationsJSONRequestBody = CreateOrganizationRequest

// PatchV1OrganizationsIdJSONRequestBody defines body for PatchV1OrganizationsId for application/json ContentType.
type PatchV1OrganizationsIdJSONRequestBody = UpdateOrganizationRequest
