// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for HealthzResponseStatus.
const (
	Ok HealthzResponseStatus = "ok"
)

// Defines values for ReadyzResponseStatus.
const (
	NotReady ReadyzResponseStatus = "not_ready"
	Ready    ReadyzResponseStatus = "ready"
)

// DevAuthTokenRequest defines model for DevAuthTokenRequest.
type DevAuthTokenRequest struct {
	// ActorId UUID to embed as the "sub" (subject) claim. Defaults to 00000000-0000-0000-0000-000000000001.
	ActorId *openapi_types.UUID `json:"actor_id,omitempty"`

	// OrgId Optional organisation UUID embedded as the "org_id" claim.
	OrgId *openapi_types.UUID `json:"org_id"`

	// Roles Coarse-grained role labels embedded in the "roles" claim.
	Roles *[]string `json:"roles,omitempty"`

	// TtlSeconds Token lifetime in seconds. Defaults to 3600 (1 hour) when omitted or ≤ 0.
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// DevAuthTokenResponse defines model for DevAuthTokenResponse.
type DevAuthTokenResponse struct {
	// ActorId The actor UUID embedded in the token's sub claim.
	ActorId string `json:"actor_id"`

	// Audience The aud claim value (configured JWT_AUDIENCE).
	Audience string `json:"audience"`

	// ExpiresAt Token expiry time (RFC3339 UTC).
	ExpiresAt time.Time `json:"expires_at"`

	// Issuer The iss claim value (configured JWT_ISSUER).
	Issuer string `json:"issuer"`

	// Token Signed JWT (HS256 via jwt/v5) usable in Authorization Bearer headers.
	Token string `json:"token"`
}

// DevTokenRequest defines model for DevTokenRequest.
type DevTokenRequest struct {
	// ActorId UUIDv7 or any string identifier for the test actor. Defaults to "00000000-0000-0000-0000-000000000001".
	ActorId *string `json:"actor_id,omitempty"`

	// ActorType Actor type label embedded in the JWT claims. Defaults to "stub_user".
	ActorType *string `json:"actor_type,omitempty"`

	// Audience JWT audience claim. Defaults to the server's configured audience.
	Audience *string `json:"audience,omitempty"`

	// Roles Role list embedded in the JWT claims.
	Roles *[]string `json:"roles,omitempty"`

	// TtlSeconds Token time-to-live in seconds. Defaults to 3600.
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// DevTokenResponse defines model for DevTokenResponse.
type DevTokenResponse struct {
	// ActorId Actor ID embedded in the token
	ActorId string `json:"actor_id"`

	// ActorType Actor type embedded in the token
	ActorType string `json:"actor_type"`

	// Audience JWT audience (aud) claim
	Audience string `json:"audience"`

	// ExpiresAt Token expiry time (RFC3339)
	ExpiresAt time.Time `json:"expires_at"`

	// Issuer JWT issuer (iss) claim
	Issuer string `json:"issuer"`

	// Token Signed JWT (HS256) that can be used in Authorization headers
	Token string `json:"token"`
}

// EchoRequest defines model for EchoRequest.
type EchoRequest struct {
	// Message Message to echo. Must be non-empty. Maximum 8 KiB.
	Message string `json:"message"`
}

// EchoResponse defines model for EchoResponse.
type EchoResponse struct {
	// ActorId ID of the authenticated actor who sent the request
	ActorId string `json:"actor_id"`

	// EchoEventId UUIDv7 of the outbox_events row created for this echo (for downstream tracing)
	EchoEventId openapi_types.UUID `json:"echo_event_id"`

	// IdempotentKey The Idempotency-Key header value that was used to deduplicate this request
	IdempotentKey string `json:"idempotent_key"`

	// IssuedAt Server-side timestamp when the response was built (RFC3339Nano)
	IssuedAt time.Time `json:"issued_at"`

	// Message The echoed message from the request body
	Message string `json:"message"`

	// RequestId Per-request correlation ID
	RequestId string `json:"request_id"`

	// TraceId Distributed trace ID
	TraceId string `json:"trace_id"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		// Code Machine-readable error code in dotted-namespace format
		// (e.g. "http.not_found", "auth.token_expired", "echo.invalid_body").
		// Always lowercase; namespace component followed by dot-separated sub-codes.
		Code string `json:"code"`

		// Details Optional structured details about the error (analogous to a JSONB object).
		// May contain field-level validation errors, conflict context, or other
		// machine-readable diagnostic data. Omitted when there are no additional
		// details.
		Details *map[string]interface{} `json:"details"`

		// Message Human-readable error description (may be localised)
		Message string `json:"message"`

		// RequestId Per-request correlation ID (also in X-Request-Id response header)
		RequestId string `json:"request_id"`

		// TraceId Distributed trace ID (also in X-Trace-Id response header)
		TraceId string `json:"trace_id"`
	} `json:"error"`
}

// HealthzResponse defines model for HealthzResponse.
type HealthzResponse struct {
	// Status Always "ok" when the process is alive
	Status HealthzResponseStatus `json:"status"`
}

// HealthzResponseStatus Always "ok" when the process is alive
type HealthzResponseStatus string

// InfoResponse defines model for InfoResponse.
type InfoResponse struct {
	// ActiveLocale Locale resolved for this specific request via Accept-Language → ?lang= → default_locale negotiation
	ActiveLocale string `json:"active_locale"`

	// App Application name
	App string `json:"app"`

	// Commit Git commit SHA (short or full)
	Commit string `json:"commit"`

	// DbNow PostgreSQL now() at the time of the SELECT (omitted when DB query fails)
	DbNow *time.Time `json:"db_now,omitempty"`

	// DbVersion PostgreSQL server_version string (omitted when DB query fails)
	DbVersion *string `json:"db_version,omitempty"`

	// DefaultLocale Fallback locale when Accept-Language negotiation yields no match
	DefaultLocale string `json:"default_locale"`

	// Env Deployment environment (development, staging, production)
	Env string `json:"env"`

	// RequestId Per-request correlation ID
	RequestId string `json:"request_id"`

	// ServerTime Current UTC wall clock time on the server (RFC3339Nano)
	ServerTime time.Time `json:"server_time"`

	// SupportedLocales BCP-47 locale tags the server will accept
	SupportedLocales []string `json:"supported_locales"`

	// TraceId Distributed trace ID
	TraceId string `json:"trace_id"`

	// Version Semantic version string
	Version string `json:"version"`
}

// ReadyzResponse defines model for ReadyzResponse.
type ReadyzResponse struct {
	// Checks Map of probe name to status string ("ok" or error message)
	Checks map[string]string `json:"checks"`

	// Status "ready" when all probes pass, "not_ready" when any probe fails
	Status ReadyzResponseStatus `json:"status"`
}

// ReadyzResponseStatus "ready" when all probes pass, "not_ready" when any probe fails
type ReadyzResponseStatus string

// PostV1EchoParams defines parameters for PostV1Echo.
type PostV1EchoParams struct {
	// IdempotencyKey Client-generated UUID that uniquely identifies this mutation request.
	// Replays (same actor + same key) return the originally cached response
	// without re-executing the handler. TTL is 24 hours.
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	// Page Current page number (1-based; first page is 1)
	Page int `json:"page"`

	// PageSize Maximum number of items per page as requested by the caller
	PageSize int `json:"page_size"`

	// Total Total number of items that match the applied query filters
	Total int `json:"total"`

	// TotalPages Total number of pages computed as ceil(total / page_size)
	TotalPages int `json:"total_pages"`
}

// PostV1DevAuthTokenJSONRequestBody defines body for PostV1DevAuthToken for application/json ContentType.
type PostV1DevAuthTokenJSONRequestBody = DevAuthTokenRequest

// PostV1DevTokenJSONRequestBody defines body for PostV1DevToken for application/json ContentType.
type PostV1DevTokenJSONRequestBody = DevTokenRequest

// PostV1EchoJSONRequestBody defines body for PostV1Echo for application/json ContentType.
type PostV1EchoJSONRequestBody = EchoRequest
